Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-03, with the labels that each got.

#1362 [HOTFIX] Avoid duplicating unread separator when reconnecting
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
Labels: hotfix

#1365 [HOTFIX] Escape regex characters in emoji shortnames before parsing
  Rocket.Chat/External/RCEmojiKit/Emojione.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.ChatTests/External/RCEmojiKit/EmojioneSpec.swift
Labels: hotfix, ⏰ waiting review

#1366 [HOTFIX] Disable collapse and fix height of file attachment view
  Rocket.Chat/Models/Attachment.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextViewModel.swift
  Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift
Labels: hotfix, ⏰ waiting review

#1372 [I18N] Update greek localization for new text
  Rocket.Chat/Resources/el.lproj/Localizable.strings
Labels: 🌎 i18n

#1373 [NEW] Add authViewController localization
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Auth.storyboard
Labels: 🌎 i18n

#1374 [I18N] Spanish strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
Labels: 🌎 i18n

#1376 [I18N] Update VoiceOver.strings spanish
  Rocket.Chat/Resources/es.lproj/VoiceOver.strings
Labels: 🌎 i18n

#1377 [NEW] Interactive keyboard dismissal added to ChatViewController / [FIX] Fixed the weird scrolling behavior and layout issues on chat rooms that one hasn't joined
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.swift
  Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.xib
Labels: 🎉 feature, 👍 improvement

#1384 [IMPROVEMENT] Improvements on the App Icon selection
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/ChangeAppIconViewController.swift
  Rocket.Chat/Controllers/Settings/ChangeAppIconCell.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check Circle.imageset/Check Circle.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check Circle.imageset/Check Circle@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check Circle.imageset/Check Circle@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check Circle.imageset/Contents.json
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.Chat/Views/Cells/Preferences/ReusableViewText.swift
  Rocket.Chat/Views/Cells/Preferences/ReusableViewText.xib
Labels: 👀 needs review, 👍 improvement, 🖼 layout

#1389 [FIX] Typo on mimetype information when uploading a file
  Rocket.Chat/API/Requests/Message/UploadRequest.swift
Labels: 🐛 bug

#1395 [I18N] Translate missing polish strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/VoiceOver.strings
Labels: 🌎 i18n

#1382 [IMPROVEMENT] Interactive keyboard dismissal improved
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Views/Chat/KeyboardFrameView.swift
Labels: 👍 improvement

#1402 [BUG] App does not render preview picture for videos directly
  Rocket.Chat/Models/Attachment.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.ChatTests/Models/AttachmentSpec.swift
Labels: 🐛 bug

#1390 [IMPROVEMENT] Scroll performance improvement
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Extensions/RealmExtension.swift
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.Chat/Views/Chat/KeyboardFrameView.swift
Labels: 👍 improvement, 🚀 performance

#1401 [IMPROVEMENT] Add a better support to fullpath URL attachments
  Rocket.Chat/Models/Attachment.swift
  Rocket.ChatTests/Models/AttachmentSpec.swift
  Rocket.ChatTests/Settings/PreferencesViewModelSpec.swift
Labels: 👍 improvement

#1403 [RELEASE] Merge beta into develop
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Extensions/RealmExtension.swift
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/Attachment.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/VoiceOver.strings
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.Chat/Views/Chat/KeyboardFrameView.swift
  Rocket.ChatTests/Models/AttachmentSpec.swift
  Rocket.ChatTests/Settings/PreferencesViewModelSpec.swift
Labels: 💎 release: beta

#1406 [FIX] Terms of service and Privacy policy button spacing fixed
  Rocket.Chat/Storyboards/Auth.storyboard
Labels: 👍 improvement

#1277 [FIX] Enable support for Rocket hosted on subdirectory
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/APIRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Extensions/API/APIExtensions.swift
  Rocket.Chat/Extensions/URLExtension.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Models/Auth.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.ChatTests/Models/AuthSpec.swift
Labels: 👍 improvement, 🚧 wip: contributor, 🚫 blocked: other issue

#1368 [NEW] Let user update name, username, email, password and avatar
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/UploadClient.swift
  Rocket.Chat/API/Requests/Authentication/MeRequest.swift
  Rocket.Chat/API/Requests/Message/UploadMessageRequest.swift
  Rocket.Chat/API/Requests/User/UpdateUserRequest.swift
  Rocket.Chat/API/Requests/User/UploadAvatarRequest.swift
  Rocket.Chat/API/Requests/User/UserInfoRequest.swift
  Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
  Rocket.Chat/Controllers/Settings/EditProfileTableViewController.swift
  Rocket.Chat/Controllers/Settings/EditProfileViewModel.swift
  Rocket.Chat/Controllers/Settings/NewPasswordTableViewController.swift
  Rocket.Chat/Controllers/Settings/NewPasswordViewModel.swift
  Rocket.Chat/Controllers/Settings/PreferencesViewController.swift
  Rocket.Chat/Controllers/Settings/PreferencesViewModel.swift
  Rocket.Chat/Extensions/UIColorExtension.swift
  Rocket.Chat/Extensions/UINavigationControllerExtension.swift
  Rocket.Chat/Extensions/UIViewControllerExtension.swift
  Rocket.Chat/Helpers/Alert.swift
  Rocket.Chat/Models/Mapping/UserModelMapping.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Camera.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Camera.imageset/camera.pdf
  Rocket.Chat/Resources/Assets.xcassets/Icons/Checkmark.imageset/Checkmark.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Checkmark.imageset/Checkmark@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Checkmark.imageset/Checkmark@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Checkmark.imageset/Contents.json
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Rocket.Chat-Bridge.h
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.ChatTests/API/Requests/Message/UploadMessageRequestSpec.swift
  Rocket.ChatTests/API/Requests/User/UpdateUserRequestSpec.swift
  Rocket.ChatTests/API/Requests/User/UploadAvatarRequestSpec.swift
  Rocket.ChatTests/API/Requests/User/UserInfoRequestSpec.swift
  Rocket.ChatTests/Settings/PreferencesViewModelSpec.swift
Labels: 🎉 feature, 👀 needs review

#1412 [FIX] Make some adjustments on the connect screen & improve pt-BR translation
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Auth.storyboard
Labels: 🌎 i18n, 🖼 layout

#1416 [IMPROVEMENT] Add more tests to Profile feature
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.ChatTests/Settings/EditProfileViewModelSpec.swift
  Rocket.ChatTests/Settings/NewPasswordViewModelSpec.swift
Labels: 👍 improvement

#1415 [FIX] Invalid url path building
  Rocket.Chat/API/APIRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
Labels: 🐛 bug, 👀 needs review

#1411 [NEW] Add the possibility to set default browser
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Settings/PreferencesViewController.swift
  Rocket.Chat/Controllers/Settings/PreferencesViewModel.swift
  Rocket.Chat/Controllers/Settings/WebBrowserTableViewController.swift
  Rocket.Chat/Controllers/Settings/WebBrowserViewModel.swift
  Rocket.Chat/Extensions/UIWindowExtensions.swift
  Rocket.Chat/Helpers/Alert.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/WebBrowserManager.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.ChatTests/Managers/WebBrowserManagerSpec.swift
  Rocket.ChatTests/Settings/PreferencesViewModelSpec.swift
  Rocket.ChatTests/Settings/WebBrowserViewModelSpec.swift
Labels: 🎉 feature, 👀 needs review

#1417 [IMPROVEMENT] Improved the scrolling performance of the emoji picker
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiCollectionViewCell.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiCollectionViewCell.xib
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiView.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiView.xib
Labels: 👍 improvement

#1418 [CHORE] Use BODY & change detail color into settings labels
  Rocket.Chat/Storyboards/Preferences.storyboard
Labels: 👍 improvement, 🚚 chore

#1420 [FIX] FLEX cell in Preferences wasn't being selected
  Rocket.Chat/Controllers/Settings/PreferencesViewController.swift
Labels: 🐛 bug

#1439 [NEW] Support "Edit Profile" settings
  Rocket.Chat/Controllers/Settings/EditProfileTableViewController.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
Labels: 🎉 feature

#1441 [RELEASE] Increment build version to 2.1.0 (150)
  Rocket.Chat/Info.plist
Labels: 💎 release: beta, 🛠 project

#1440 [IMPROVEMENT] Improving project build time
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/Emojione.swift
  Rocket.Chat/External/RCEmojiKit/Emojis/activity.json
  Rocket.Chat/External/RCEmojiKit/Emojis/flags.json
  Rocket.Chat/External/RCEmojiKit/Emojis/food.json
  Rocket.Chat/External/RCEmojiKit/Emojis/nature.json
  Rocket.Chat/External/RCEmojiKit/Emojis/objects.json
  Rocket.Chat/External/RCEmojiKit/Emojis/people.json
  Rocket.Chat/External/RCEmojiKit/Emojis/regional.json
  Rocket.Chat/External/RCEmojiKit/Emojis/symbols.json
  Rocket.Chat/External/RCEmojiKit/Emojis/travel.json
  Rocket.Chat/External/RCEmojiKit/emojiNames.json
Labels: 🛠 project

#1444 [IMPROVEMENT] Profile auth settings tests
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Settings/EditProfileTableViewController.swift
  Rocket.Chat/Managers/WindowManager.swift
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.swift
  Rocket.ChatTests/Controllers/EditProfileTableViewControllerSpec.swift
Labels: ✅ tests, 👍 improvement

#1445 [CHORE] Add more information on crash of Crashlytics
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
  Rocket.Chat/Managers/Model/AuthManager.swift
  Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
Labels: 👍 improvement

#1451 [HOTFIX] App hanging on emoji parsing sometimes
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/Emojione.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Models/CustomEmoji.swift
Labels: 👀 needs review, 🔥 hotfix

#1453 [CHORE] Revert back Starscream to 2.1.1 to prevent loosing connection on WebSocket
  Podfile
  Podfile.lock
  Rocket.Chat/Managers/Socket/SocketManager.swift
Labels: ⬆️ update dependencies, 🐛 bug

#1450 [NEW] Placeholder on authentication fields via Settings
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
Labels: 🎉 feature

#1454 [CHORE] Increment build number
  Rocket.Chat/Info.plist
Labels: 💎 release: beta

#1455 [RELEASE] Merge develop into beta
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Settings/EditProfileTableViewController.swift
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/Emojione.swift
  Rocket.Chat/External/RCEmojiKit/Emojis/activity.json
  Rocket.Chat/External/RCEmojiKit/Emojis/flags.json
  Rocket.Chat/External/RCEmojiKit/Emojis/food.json
  Rocket.Chat/External/RCEmojiKit/Emojis/nature.json
  Rocket.Chat/External/RCEmojiKit/Emojis/objects.json
  Rocket.Chat/External/RCEmojiKit/Emojis/people.json
  Rocket.Chat/External/RCEmojiKit/Emojis/regional.json
  Rocket.Chat/External/RCEmojiKit/Emojis/symbols.json
  Rocket.Chat/External/RCEmojiKit/Emojis/travel.json
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/External/RCEmojiKit/emojiNames.json
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Managers/Model/AuthManager.swift
  Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Managers/WindowManager.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.swift
  Rocket.ChatTests/Controllers/EditProfileTableViewControllerSpec.swift
Labels: 💎 release: beta

#1458 [BUG] Persist user e-mail to realm
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Models/Email.swift
  Rocket.Chat/Models/Mapping/UserModelMapping.swift
Labels: 👍 improvement

#1463 [FIX] Crash when alternating servers
  Rocket.Chat/API/Clients/CommandsClient.swift
  Rocket.Chat/API/Clients/InfoClient.swift
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Extensions/Models/UserExtensions.swift
  Rocket.Chat/Extensions/RealmExtension.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Model/AuthManager.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Model/CustomEmojiManager.swift
  Rocket.Chat/Managers/Model/LoginServiceManager.swift
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.Chat/Managers/Model/PermissionManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager.swift
  Rocket.Chat/Models/Auth.swift
  Rocket.Chat/Models/Base/BaseModel.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.Chat/Models/Subscription.swift
  Rocket.Chat/Models/User.swift
  Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.swift
  Rocket.ChatTests/Models/BaseModelSpec.swift
Labels: 🐛 bug

#1459 [FIX] Not persisting server version
  Rocket.Chat/Managers/Model/AuthManager.swift
Labels: 🐛 bug

#1464 [FIX] Addresses prolonged freezes in some chat rooms
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/Emojione.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.ChatTests/External/RCEmojiKit/EmojioneSpec.swift
Labels: 👍 improvement

#1468 [CHORE] Increment version of the app to 2.1.1 (152)
  Rocket.Chat/Info.plist
Labels: 💎 release: beta
