Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-11, with the labels that each got.

#2271 [IMPROVEMENT] Minor layout improvements and performance improvements
  Podfile.lock
  Pods/Manifest.lock
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Pods/Target Support Files/DifferenceKit/DifferenceKit-Info.plist
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManagerSystemMessages.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/Subscription/SubscriptionQueries.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
  Rocket.Chat/Models/Subscription/UnmanagedSubscription.swift
  Rocket.Chat/Models/UnmanagedObject.swift
  Rocket.Chat/Models/User/UnmanagedUser.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
  Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
  Rocket.ChatTests/Managers/MessageManagerSpec.swift
  Rocket.ChatTests/Models/MessageSpec.swift
  Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift
Labels: 🎉 feature

#2272 [FIX] Crash when tapping on collapsible quote
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseTextAttachmentChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift
Labels: 🎉 feature, 🐛 bug

#2281 [BUG] Missing data on the list & fixed unit tests
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
  Rocket.ChatTests/Views/AvatarViewSpec.swift
Labels: 🐛 bug

#2279 [IMPROVEMENT] Performance improvements, code simplification & prefetch one more page from database
  Podfile.lock
  Pods/Manifest.lock
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Pods/RocketChatViewController/RocketChatViewController/Classes/UIKitExtension.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
  Rocket.Chat/Models/User/UnmanagedUser.swift
  Rocket.Chat/Models/User/User.swift
  Rocket.Chat/Models/User/UserUtils.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoUserCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
  Rocket.ChatTests/Views/AvatarViewSpec.swift
Labels: 👍 improvement

#2282 [FIX] Recalculate sequential messages size when they were not sequential before an update
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 👍 improvement

#2285 [FIX] Light keyboard showing in dark themes in composer
  Rocket.Chat/Theme/ThemeableViews.swift
Labels: 🎉 feature

#2286 [FIX] Add trailing space after autocompletion
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
Labels: 👍 improvement

#2293 [CHORE] Update RocketChatViewController to reflect latest fixes
  Podfile.lock
  Pods/Local Podspecs/RocketChatViewController.podspec.json
  Pods/Manifest.lock
  Pods/RocketChatViewController/Composer/Classes/Addons/Hints/TextHintCell.swift
  Pods/RocketChatViewController/Composer/Classes/Addons/Hints/UserHintCell.swift
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Labels: ⬆️ update dependencies, 🚚 chore

#2291 [IMPROVEMENT] Performance improvements on the list and a pack with other improvements
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCellProtocol.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
Labels: 👍 improvement, 🚀 performance, 🚚 chore

#2296 [FIX] Keyboard return not sending message on new composer
  Pods/RocketChatViewController/Composer/Classes/Delegate/ComposerViewDelegate.swift
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerReplying.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerSending.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerUploading.swift
Labels: 🎉 feature

#2298 [FIX] UI call being made on background thread to fetch current theme
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 🐛 bug

#2301 [FIX][RCVC] Reintroduce iPad chat empty state
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Labels: 🐛 bug

#2299 [CHORE] Use dataSorted to calculate cell's size
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 🚚 chore

#2300 [NEW][RCVC] Reintroduce all shortcuts & message searching
  Rocket.Chat/Controllers/Base/Main/MainSplitViewControllerShortcuts.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Helpers/ShortcutHelpers.swift
Labels: 🎉 feature

#2306 [CHORE] Remove identify/anonymize mechanisms from AnalyticsCoordinator
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Launcher/AnalyticsCoordinator.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Labels: 🚚 chore

#2308 [FIX] Reintroduce message drafting
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessageViewControllerEmptyState.swift
  Rocket.Chat/Controllers/Chat/MessageViewControllerSearching.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerDrafting.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerSending.swift
Labels: 🐛 bug

#2309 [FIX] Freezing video thumb generation & race condition on data
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseVideoMessageCell.swift
  Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift
Labels: 🐛 bug

#2310 [NEW] Add support to "Loader Cell" on the top of the list
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/LoaderCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/LoaderCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/LoaderChatItem.swift
Labels: 🎉 feature

#2312 [FIX] Open Keyboard when replying
  Rocket.Chat/Controllers/Chat/MessagesViewControllerEditing.swift
Labels: 🐛 bug

#2315 [CHORE] Update our SDK version with spacing adjustments
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
Labels: ⬆️ update dependencies

#2314 [NEW] Typing status on the new title view
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessagesSubscriptionViewModel.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Model/AuthSettingsManagerPersistencyExtension.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerTyping.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
  Rocket.Chat/Models/Subscription/UnmanagedSubscription.swift
  Rocket.Chat/Models/User/UnmanagedUser.swift
  Rocket.Chat/Models/User/User.swift
  Rocket.Chat/Models/User/UserUtils.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Player Pause.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Player Pause.imageset/Player Pause.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Player Pause.imageset/Player Pause@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Player Pause.imageset/Player Pause@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Player Play.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Player Play.imageset/Player Play.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Player Play.imageset/Player Play@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Player Play.imageset/Player Play@3x.png
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Chat/ChatTitleView.swift
  Rocket.Chat/Views/Chat/ChatTitleView.xib
  Rocket.Chat/Views/Chat/ChatTitleViewModel.swift
  Rocket.ChatTests/Views/Chat/ChatTitleViewModelSpec.swift
Labels: 🎉 feature

#2320 [CHORE] Refactor scroll to bottom
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Labels: 🚚 chore

#2317 [NEW] Add back reactions handler, fix missing delegate reference and more
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Extensions/UIColorExtension.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageActionButtonsView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/ReactionsChatItem.swift
Labels: 🎉 feature

#2327 [BUG] Avatars for Subscription not using the `#` char on the URL
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Labels: 🐛 bug

#2333 [FIX] Include path in OAuth callback url building
  Rocket.Chat/Managers/OAuthManager.swift
  Rocket.ChatTests/Managers/OAuthManagerSpec.swift
Labels: 🐛 bug

#2316 [FIX][RCVC] Reintroduce room join feature
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerEmptyState.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerJoining.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerSearching.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Labels: 🐛 bug

#2335 [CHORE] Only use unmanaged objects on transforming markdown cache
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Extensions/Models/SubscriptionLastMessage.swift
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
  Rocket.ChatTests/Models/SubscriptionLastMessageSpec.swift
Labels: 🚚 chore

#2330 [NEW] Add purpose label to quote component
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Extensions/Models/MessageExtensions.swift
  Rocket.Chat/Extensions/Models/SubscriptionLastMessage.swift
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift
  Rocket.ChatTests/Models/SubscriptionLastMessageSpec.swift
Labels: 🎉 feature

#2339 [CHORE] Update RocketChatViewController
  Podfile.lock
  Pods/Local Podspecs/RocketChatViewController.podspec.json
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Assets/cs.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/de.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/el.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/en.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/es.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/fr.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/ja.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/pl.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/pt-BR.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/pt-PT.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/ru.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Classes/Addons/Editing/EditingView.swift
  Pods/RocketChatViewController/Composer/Classes/Library/ComposerLocalizable.swift
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Labels: 🚚 chore

#2342 [IMPROVEMENT] Change from fixed constraints to relative ones
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
Labels: 👍 improvement

#2341 [CHORE] Support empty title & alias on the message
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/AudioMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseTextAttachmentChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BasicMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/FileMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/ImageMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/SequentialMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/VideoMessageChatItem.swift
Labels: 🎉 feature

#2340 [NEW] Add support to play a video from the cell
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseVideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/VideoMessageChatItem.swift
Labels: 🎉 feature

#2343 [FIX] Adjust missing constraint in TextAttachmentCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
Labels: 🐛 bug

#2345 [WIP][FIX] Collapsible cells & user initiated interaction flow generally
  Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Extensions/StringExtensions.swift
  Rocket.Chat/Models/Attachment/Attachment.swift
  Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
  Rocket.Chat/Models/Mapping/MessageModelMapping.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
Labels: 🐛 bug

#2349 [IMPROVEMENT] Fixes & support to Dynamic Type on all auth flow
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Buttons/StyledButton.swift
  Rocket.Chat/Views/Cells/Auth/EmailAuthTableViewCell.xib
  Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.xib
  Rocket.Chat/Views/TextFields/StyledTextField.swift
Labels: ♿️ accessibility

#2348 [IMPROVEMENT][PERFORMANCE] Optimize size calculation performance on messages cell
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesSizingManager.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Read.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Read.imageset/Read.pdf
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Unread.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Unread.imageset/Unread.pdf
  Rocket.Chat/Resources/Assets.xcassets/Read.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Read.imageset/read.png
  Rocket.Chat/Resources/Assets.xcassets/Read.imageset/read@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Read.imageset/read@3x.png
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Buttons/StyledButton.swift
  Rocket.Chat/Views/Cells/Auth/EmailAuthTableViewCell.xib
  Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.xib
  Rocket.Chat/Views/Cells/Chat/ChatMessageURLView.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/LoaderCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/TextFields/StyledTextField.swift
  Rocket.ChatTests/Theme/ThemeableSpec.swift
Labels: 🚀 performance

#2350 [NEW] Add sharing & reviewing to preferences
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewModel.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.ChatTests/Preferences/PreferencesViewModelSpec.swift
Labels: 🎉 feature

#2351 [FIX][RCVC] Inverted scrolling shortcuts
  Rocket.Chat/Controllers/Base/Main/MainSplitViewControllerShortcuts.swift
Labels: 🐛 bug

#2353 [FIX] Updates on Subscription weren't being reflect on the database
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Labels: 🐛 bug

#2352 [FIX] Fixed bugs on Theming that was causing the Subscriptions cells to not be applied
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Labels: 🐛 bug

#2355 [FIX][RCVC] Only return to send on iPad
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
Labels: 🐛 bug

#2356 [FIX] Long names with read receipt are breaking the date field
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
Labels: 🐛 bug

#2358 [FIX] Fixed quote attachment resizing
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
Labels: 🐛 bug

#2368 [CHORE] Remove user from crash reports
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Launcher/AnalyticsCoordinator.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Labels: 🚚 chore

#2369 [BUG][RCVC] Long-press & tapping username/avatar is not being handled by cells with attachments
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseFileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseVideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/AudioMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseTextAttachmentChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BasicMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/FileMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/ImageMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/MessageActionsChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/MessageURLChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/SequentialMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/VideoMessageChatItem.swift
Labels: 🐛 bug

#2371 [NEW] Support newline in composer & soft return on external keyboards
  Rocket.Chat/Controllers/Base/Main/MainSplitViewControllerShortcuts.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🎉 feature

#2373 [RELEASE] Merge release 3.1.2 into MASTER
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Launcher/AnalyticsCoordinator.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Labels: 💎 release: master

#2375 [FIX] Crash on opening members list
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/General/DirectoryRequest.swift
  Rocket.Chat/API/Requests/Message/ReadReceiptsRequest.swift
  Rocket.Chat/Controllers/Chat/AddUsersViewController.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Models/User/UnmanagedUser.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
  Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListView.swift
  Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListViewController.swift
Labels: 💥 crash

#2380 [FIX] Composer disappearing after app store review
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
Labels: 🐛 bug

#2381 [FIX] Realm write operations outside write transaction
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
Labels: 🐛 bug

#2387 [NEW] Add border to all new components attachments/boxes
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionView.swift
  Rocket.Chat/Theme/Theme.swift
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
Labels: 🌈 theme, 👍 improvement

#2389 [FIX] Disable theming in onboarding views
  Rocket.Chat/Controllers/Auth/AuthNavigationController.swift
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Controllers/Auth/CASViewController.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/LegalTableViewController.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Controllers/Auth/OAuthViewController.swift
  Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
  Rocket.Chat/Controllers/Auth/SAMLViewController.swift
  Rocket.Chat/Controllers/Auth/SignupCustomFieldsTableViewController.swift
  Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
  Rocket.Chat/Controllers/Auth/TwoFactorAuthTableViewController.swift
  Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.Chat/Theme/NotThemeableViews.swift
  Rocket.Chat/Views/Cells/Auth/AuthSeparatorTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/CustomFieldTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/EmailAuthTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/ShowMoreSeparatorTableViewCell.swift
Labels: 🌈 theme, 🐛 bug

#2390 [IMPROVEMENT] Quoted Attachment improvements
  Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
  Rocket.Chat/Models/Mapping/MessageModelMapping.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
Labels: 👍 improvement
