Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-09, with the labels that each got.

#2166 [CRASH] Validate Subscription object before using it
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Info.plist
Labels: 💥 crash

#2167 [FIX] Not opening correct room after tapping notification when in other server
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/PushManager.swift
Labels: 🐛 bug, 👀 needs review

#2171 [RELEASE] Merge DEVELOP into BETA
  Podfile.lock
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/AnalyticsManager.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/PushManager.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/InfoPlist.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift
  Scripts/Localize.swift
Labels: 💎 release: beta

#2173 [FIX] Fix some problems with registration
  Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
  Rocket.Chat/Managers/Socket/Response/SocketError.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
Labels: 🐛 bug

#2155 [CHORE] Use latest swift for all pods
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Room/RoomRolesRequest.swift
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Extensions/ListExtension.swift
  Rocket.Chat/Helpers/DeepLink.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.Chat/Models/Mapping/PermissionModelMapping.swift
  Rocket.Chat/Models/Mapping/UserModelMapping.swift
  Rocket.ChatTests/Managers/PermissionManagerSpec.swift
Labels: 🚚 chore

#2176 [CRASH] Fixed crash on reusing cells for Auth controller
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
Labels: 💥 crash

#2185 [HOTFIX] Incorrect index path on tapping a cell in subscriptions VC
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
Labels: 💥 crash, 🔥 hotfix

#2188 [CHORE] Update subtitle on Welcome screen to "Team Communication"
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🖼 layout, 🚚 chore

#2187 [FIX] Crash on invalid subscription managed object
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Labels: 💥 crash

#2186 [FIX] Roles would be cleaned on viewing the list of Members
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Room/RoomMembersRequest.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Models/Mapping/UserModelMapping.swift
  Rocket.Chat/Models/User/UserPermissions.swift
Labels: 🐛 bug

#2182 [IMPROVEMENT] Remove defaults to open.rocket.chat & add a new placeholder to the connection field
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Buttons/StyledButton.swift
Labels: 👍 improvement

#2180 [NEW] Handle system/private messages stream
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManagerSystemMessages.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.ChatTests/Managers/MessageManagerSpec.swift
  Rocket.ChatTests/Managers/MessageManagerSystemMessageSpec.swift
Labels: 🎉 feature

#2189 [BUG + UPDATES] Update Realm & Firebase, fixed bug introduced on Community button and fixed a bug with long chats name
  Podfile.lock
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Views/Chat/ChatTitleView.xib
Labels: ⬆️ update dependencies, 🐛 bug

#2190 [IMPROVEMENT] Theme background for code blocks and markdown quotes
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Managers/MarkdownManager.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
Labels: 🌈 theme, 👍 improvement

#2199 [CHORE] Increment version of the app for a new release
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
Labels: 🚚 chore

#2207 [CI] Use iOS 11.2 in place of 11.3 for circle CI
  circle.yml
Labels: 👷 ci

#2209 [CHORE] Log the opening of the admin to understand the usage of it
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Managers/AnalyticsManager.swift
Labels: 📊 analytics

#2213 [CHORE] Add TestFlight invitation link to the README
  README.md
Labels: 📝 docs

#2204 [IMPROVEMENT] Basic message structure
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesSizingManager.swift
  Rocket.Chat/Controllers/Chat/MessagesSubscriptionViewModel.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Helpers/MessageTextFontAttributes.swift
  Rocket.Chat/Helpers/RealmAssorter.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
  Rocket.Chat/Models/ChatModels/MessageSectionModel.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/Subscription/UnmanagedSubscription.swift
  Rocket.Chat/Models/UnmanagedObject.swift
  Rocket.Chat/Models/User/UnmanagedUser.swift
  Rocket.Chat/Models/User/User.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BasicMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/DateSeparatorChatItem.swift
  Rocket.Chat/Views/Chat/RCTextView.swift
  Rocket.ChatTests/Controllers/MessagesSizingViewModelSpec.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
Labels: 👍 improvement

#2220 [NEW] Reactions new component
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionView.xib
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/ReactionsChatItem.swift
  Rocket.ChatTests/Controllers/MessagesSizingViewModelSpec.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
  Rocket.ChatTests/Managers/MessageManagerSpec.swift
Labels: 🎉 feature

#2219 [NEW] Video component new layout
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionView.xib
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Video/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Video/Player Video.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Video/Player Video.imageset/Player Video.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Video/Player Video.imageset/Player Video@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/Video/Player Video.imageset/Player Video@3x.png
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/ReactionsChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/VideoMessageChatItem.swift
  Rocket.ChatTests/Controllers/MessagesSizingViewModelSpec.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
  Rocket.ChatTests/Managers/MessageManagerSpec.swift
Labels: 🎉 feature

#2225 [NEW] File attachment
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Assets.xcassets/iconFilesGeneric.imageset/Contents.json
  Rocket.Chat/Assets.xcassets/iconFilesGeneric.imageset/iconFilesGeneric.png
  Rocket.Chat/Assets.xcassets/iconFilesGeneric.imageset/iconFilesGeneric@2x.png
  Rocket.Chat/Assets.xcassets/iconFilesGeneric.imageset/iconFilesGeneric@3x.png
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/iconFilesGeneric.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/iconFilesGeneric.imageset/iconFilesGeneric.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/iconFilesGeneric.imageset/iconFilesGeneric@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/iconFilesGeneric.imageset/iconFilesGeneric@3x.png
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/FileMessageChatItem.swift
Labels: 🎉 feature
