Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-10, with the labels that each got.

#2228 [NEW] Image component
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/ImageMessageChatItem.swift
Labels: 🎉 feature

#2224 [NEW] Support autocompletion in new composer
  Podfile.lock
  Pods/Manifest.lock
  Pods/RocketChatViewController/Composer/Classes/Addons/Hints/HintsView.swift
  Pods/RocketChatViewController/Composer/Classes/Addons/Hints/UserHintCell.swift
  Pods/RocketChatViewController/Composer/Classes/Delegate/ComposerViewExpandedDelegate.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessagesComposerViewModel.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Avatar/AvatarView.xib
  Rocket.Chat/Views/Cells/Chat/AutocompleteCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoUserCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Notification/NotificationView.swift
  Rocket.ChatTests/Views/AvatarViewSpec.swift
Labels: 🎉 feature

#2227 [NEW] Text Attachment
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerButton.swift
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Pods/RocketChatViewController/RocketChatViewController/Classes/UIKitExtension.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesSizingManager.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Resources/Assets.xcassets/Attachment Collapsed Light.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Attachment Collapsed Light.imageset/disclosureCopy.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Collapsed Light.imageset/disclosureCopy@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Collapsed Light.imageset/disclosureCopy@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Expanded Light.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Attachment Expanded Light.imageset/disclosure.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Expanded Light.imageset/disclosure@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Expanded Light.imageset/disclosure@3x.png
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AttachmentFieldView.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AttachmentFieldView.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift
Labels: 🎉 feature

#2237 [FIX] Emoji autocompletion in new composer
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Classes/Addons/Hints/TextHintCell.swift
  Pods/RocketChatViewController/Composer/Classes/Addons/Reply/ReplyView.swift
  Pods/RocketChatViewController/Composer/Classes/Delegate/ComposerViewDelegate.swift
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerButton.swift
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerTextView.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessagesComposerViewModel.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Extensions/EmojiView/EmojiViewSetEmoji.swift
Labels: 🐛 bug

#2231 [IMPROVEMENT] Enabled clearButton on the email TextField at ForgotPassword
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Labels: 👍 improvement

#2239 [IMPROVEMENTS] Bug fixes & improvements on the new composer & components
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Models/ChatModels/MessageSectionModel.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
Labels: 🐛 bug, 👍 improvement

#2242 [BUG] Duplicated data on receiving modifications from Realm
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 🐛 bug

#2244 [IMPROVEMENT] Cell sizing
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
Labels: 👍 improvement

#2246 [CHORE] Resolve couple code warnings in the project
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Extensions/RealmCurrent.swift
  Rocket.Chat/Extensions/RealmExecute.swift
  Rocket.Chat/Managers/Launcher/TestingCoordinator.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
  Rocket.ChatTests/API/Clients/CommandsClientSpec.swift
  Rocket.ChatTests/API/Clients/InfoClientSpec.swift
  Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
  Rocket.ChatTests/API/Clients/SpotlightClientSpec.swift
  Rocket.ChatTests/API/Requests/Message/ReactMessageRequestSpec.swift
  Rocket.ChatTests/Extensions/API/APIExtensionsSpec.swift
  Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
  Rocket.ChatTests/Extensions/Models/UserExtensionsSpec.swift
  Rocket.ChatTests/Managers/MessageManagerSystemMessageSpec.swift
  Rocket.ChatTests/Managers/PermissionManagerSpec.swift
  Rocket.ChatTests/Models/Auth/AuthSpec.swift
  Rocket.ChatTests/Models/CustomEmojiSpec.swift
  Rocket.ChatTests/Models/MessageSpec.swift
  Rocket.ChatTests/Models/UserSpec.swift
Labels: 🚚 chore

#2247 [IMPROVEMENT] Transform all relationships with Message unmanaged by Realm
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerDocuments.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Models/Attachment/Attachment.swift
  Rocket.Chat/Models/Attachment/UnmanagedAttachment.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/FileMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/ReactionsChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift
  Rocket.ChatTests/Models/UnmanagedMessageSpec.swift
Labels: 👍 improvement

#2253 [IMPROVEMENT] DataController fetching partial database messages and code improvements
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
Labels: 👍 improvement

#2256 [IMPROVEMENT] Move data processing to the background, organize better the file and fixed many bugs related to the data control
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 👍 improvement

#2258 [IMPROVEMENT] Chat theming performance
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
Labels: 👍 improvement, 🚀 performance

#2257 [CHORE] Update API endpoint of Permissions list
  Rocket.Chat/API/Requests/General/PermissionsRequest.swift
Labels: 🚚 chore

#2259 [NEW] Read receipt
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Extensions/UIViewExtentions.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Resources/Assets.xcassets/Read.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Read.imageset/read.png
  Rocket.Chat/Resources/Assets.xcassets/Read.imageset/read@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Read.imageset/read@3x.png
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseAudioMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseFileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseVideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/AudioMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BaseMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/BasicMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/FileMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/ImageMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/QuoteChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/SequentialMessageChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/TextAttachmentChatItem.swift
  Rocket.Chat/Views/Chat/New Chat/ChatItems/VideoMessageChatItem.swift
Labels: 🎉 feature

#2260 [NEW] Broadcast reply/Message actions
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Models/User/UnmanagedUser.swift
  Rocket.Chat/Resources/Assets.xcassets/back.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/back.imageset/back.png
  Rocket.Chat/Resources/Assets.xcassets/back.imageset/back@2x.png
  Rocket.Chat/Resources/Assets.xcassets/back.imageset/back@3x.png
  Rocket.Chat/Views/Cells/Chat/ChatMessageActionButtonsView.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/MessageActionsChatItem.swift
Labels: 🎉 feature

#2261 [CHORE] Update DifferenceKit & improvements on the data controller, also fixes unit tests
  Podfile.lock
  Pods/DifferenceKit/README.md
  Pods/DifferenceKit/Sources/Algorithm.swift
  Pods/DifferenceKit/Sources/AnyDifferentiable.swift
  Pods/DifferenceKit/Sources/ArraySection.swift
  Pods/DifferenceKit/Sources/Changeset.swift
  Pods/DifferenceKit/Sources/ContentEquatable.swift
  Pods/DifferenceKit/Sources/Differentiable.swift
  Pods/DifferenceKit/Sources/ElementPath.swift
  Pods/DifferenceKit/Sources/Extensions/UIKitExtension.swift
  Pods/DifferenceKit/Sources/StagedChangeset.swift
  Pods/Local Podspecs/RocketChatViewController.podspec.json
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Pods/Target Support Files/DifferenceKit-Core/Info.plist
  Pods/Target Support Files/DifferenceKit/Info.plist
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
Labels: ⬆️ update dependencies, 🚚 chore

#2262 [NEW] Add support to "Unread Marker" on the list of messages
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Extensions/UIColorExtension.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/UnreadMarkerChatItem.swift
Labels: 🎉 feature

#2266 [NEW] Components theming and ui adjustments
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Helpers/MessageTextFontAttributes.swift
  Rocket.Chat/Managers/MarkdownManager.swift
  Rocket.Chat/Resources/Assets.xcassets/Attachment Collapsed Dark.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Attachment Collapsed Dark.imageset/disclosureCopy.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Collapsed Dark.imageset/disclosureCopy@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Collapsed Dark.imageset/disclosureCopy@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Expanded Dark.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Attachment Expanded Dark.imageset/disclosure.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Expanded Dark.imageset/disclosure@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Attachment Expanded Dark.imageset/disclosure@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/iconFilesGeneric.imageset/iconFilesGeneric.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/iconFilesGeneric.imageset/iconFilesGeneric@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Cells/iconFilesGeneric.imageset/iconFilesGeneric@3x.png
  Rocket.Chat/Resources/Assets.xcassets/files.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/files.imageset/files.png
  Rocket.Chat/Resources/Assets.xcassets/files.imageset/files@2x.png
  Rocket.Chat/Resources/Assets.xcassets/files.imageset/files@3x.png
  Rocket.Chat/Theme/Theme.swift
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AttachmentFieldView.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseAudioMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
Labels: 👍 improvement

#2267 [CHORE] Refactor chat theme adoption
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Theme/ThemeableViews.swift
Labels: 👍 improvement

#2270 [IMPROVEMENT] Reflect data changes on dataSorted and dataNormalized
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Labels: 🐛 bug

#2269 [NEW] Components interspacing
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionListView.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/AudioMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/FileMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageActionsCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ReactionsCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
Labels: 👍 improvement
