Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-05, with the labels that each got.

#1523 [NEW] Allow user to see all attachments in a channel/group/DM
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Subscription/SubscriptionFilesRequest.swift
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Controllers/Subscriptions/AudioFileViewController.swift
  Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
  Rocket.Chat/Models/File.swift
  Rocket.Chat/Models/Mapping/FileModelMapping.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/audio.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/audio.imageset/audio@1x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audio.imageset/audio@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audio.imageset/audio@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audioLarge.imageset/Audio Large@1x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audioLarge.imageset/Audio Large@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audioLarge.imageset/Audio Large@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audioLarge.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/icon_file.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/icon_file.imageset/icon_file.png
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Views/Cells/Chat/ChatMessageAudioView.swift
  Rocket.Chat/Views/Cells/LoaderTableViewCell.xib
  Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift
  Rocket.Chat/Views/Subscriptions/FileTableViewCell.xib
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionFilesRequestSpec.swift
Labels: 🎉 feature

#1627 [RELEASE] Merge beta into develop
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Subscription/SubscriptionFilesRequest.swift
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Controllers/Subscriptions/AudioFileViewController.swift
  Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/File.swift
  Rocket.Chat/Models/Mapping/FileModelMapping.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/audio.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/audio.imageset/audio@1x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audio.imageset/audio@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audio.imageset/audio@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audioLarge.imageset/Audio Large@1x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audioLarge.imageset/Audio Large@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audioLarge.imageset/Audio Large@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/audioLarge.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/icon_file.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/icon_file.imageset/icon_file.png
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Views/Cells/Chat/ChatMessageAudioView.swift
  Rocket.Chat/Views/Cells/LoaderTableViewCell.xib
  Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift
  Rocket.Chat/Views/Subscriptions/FileTableViewCell.xib
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionFilesRequestSpec.swift
Labels: 💎 release: beta

#1630 [FIX] Crash on UITextView related to handling URLs
  Rocket.Chat/Views/Chat/RCTextView.swift
Labels: 💥 crash

#1632 [FIX] Check on EmojiPicker for invalid IndexPath
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
Labels: 💥 crash

#1624 [FIX] Message pinned not rendering correctly
  Rocket.Chat/Extensions/Models/MessageExtensions.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Labels: 🐛 bug, 👀 needs review

#1622 [IMPROVEMENT] Migrate "get permissions" API request to HTTP
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/InfoClient.swift
  Rocket.Chat/API/Requests/General/PermissionsRequest.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.ChatTests/API/Clients/InfoClientSpec.swift
  Rocket.ChatTests/API/Requests/General/PermissionsRequestSpec.swift
Labels: 👀 needs review, 👍 improvement, 📡 networking

#1623 [IMPROVEMENT] Migrate pin and unpin message request to HTTP
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Requests/Message/PinMessageRequest.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.ChatTests/API/Requests/Message/PinMessageRequestSpec.swift
Labels: 👀 needs review, 👍 improvement, 📡 networking

#1638 [IMPROVEMENT] Migrate request that marks subscription as read to HTTP
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionReadRequest.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionReadRequestSpec.swift
Labels: 👍 improvement, 📡 networking

#1640 [FIX] Infinite loader on the top for very small conversations (without scrolling)
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Managers/Model/MessageManager.swift
Labels: 🐛 bug

#1643 [FIX] Unread separator
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
Labels: 🐛 bug

#1633 [RELEASE] Merge beta into develop
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Chat/RCTextView.swift
Labels: 💎 release: beta

#1644 [IMPROVEMENT] Migrate login network request to HTTP
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/AuthClient.swift
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Authentication/LoginRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/TwoFactorAuthenticationViewController.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.ChatTests/API/Requests/Authentication/LoginRequestSpec.swift
Labels: 👀 needs review, 👍 improvement, 📡 networking

#1647 [CHORE] Update Realm and SwiftyJSON
  Podfile.lock
Labels: ⬆️ update dependencies

#1649 [IMPROVEMENT] Notification font size changed
  Rocket.Chat/Controllers/Notification/NotificationViewController.swift
  Rocket.Chat/Controllers/Notification/NotificationViewController.xib
Labels: 🖼 layout

#1641 [NEW] Show user action sheet in reactor list
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Auth/CASViewController.swift
  Rocket.Chat/Controllers/Auth/SAMLViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Extensions/UIViewController/UIViewControllerExtension.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListViewController.swift
  Rocket.Chat/Helpers/Closeable.swift
  Rocket.Chat/Views/ActionSheets/UserActionSheetPresenter.swift
Labels: 🎉 feature

#1651 [FIX] Infinite recursion on APIError description
  Rocket.Chat/API/APIError.swift
Labels: 💥 crash

#1655 [FIX] Fixed failing tests in develop
  Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift
  Rocket.ChatTests/Controllers/NotificationViewControllerSpec.swift
  Rocket.ChatTests/Managers/PermissionManagerSpec.swift
  Rocket.ChatTests/Models/Auth/AuthSpec.swift
  Rocket.ChatTests/Models/PermissionSpec.swift
  Rocket.ChatTests/Models/UserSpec.swift
Labels: ✅ tests

#1659 [FIX] Default english translations; German
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
Labels: 🌎 i18n

#1658 [FIX] Accessing UI from background thread
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift
Labels: 🐛 bug

#1653 [IMPROVEMENT] Migrate subscriptions & rooms fetching to HTTP
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/APIError.swift
  Rocket.Chat/API/APIRequest.swift
  Rocket.Chat/API/APIRequestOption.swift
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Command/CommandsRequest.swift
  Rocket.Chat/API/Requests/Room/RoomsRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
  Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.ChatTests/API/Clients/SubscriptionsClientSpec.swift
  Rocket.ChatTests/API/MockAPI.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomsRequestSpec.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionMembersRequestSpec.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionsRequestSpec.swift
  Rocket.ChatTests/Managers/AppManagerSpec.swift
  Rocket.ChatTests/Managers/PushManagerSpec.swift
  Rocket.ChatTests/RealmTestCase.swift
Labels: 👍 improvement, 📡 networking

#1663 [IMPROVEMENT] Change type we check for video/audio/images on the mimetype of File objects
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Models/File.swift
  Rocket.ChatTests/Models/DrawingBrushColorSpec.swift
  Rocket.ChatTests/Models/DrawingViewModelSpec.swift
  Rocket.ChatTests/Models/FileSpec.swift
Labels: 👀 needs review, 👍 improvement

#1657 [NEW] Add support to Broadcast rooms
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Subscription/SubscriptionFilesRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionRolesRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatControllerRolesController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Extensions/Models/MessageExtensions.swift
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerCurrentUser.swift
  Rocket.Chat/Models/Base/ModelMappeable.swift
  Rocket.Chat/Models/File.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Mapping/UserModelMapping.swift
  Rocket.Chat/Models/Role.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/User/User.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageActionButtonsView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageActionButtonsView.xib
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionRolesRequestSpec.swift
  Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
  Rocket.ChatTests/Models/MessageSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: 🎉 feature

#1667 [CHORE] Update CocoaPods to 1.5.2 and few libraries (Instabug & SwiftLint)
  Podfile.lock
Labels: ⬆️ update dependencies

#1670 [FIX] Choose username not working with REST API authentication
  Rocket.Chat/API/Requests/User/UpdateUserRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/RegisterUsernameViewController.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Labels: 🐛 bug, 👀 needs review

#1671 [FIX] Do not make dumb updates on Subscription mapping & update subscription object mapping on request results
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
Labels: 🐛 bug

#1672 [FIX] Crashes on Authentication, subscription optional in Message & more
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/Clients/CommandsClient.swift
  Rocket.Chat/API/Clients/InfoClient.swift
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/SignupViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/NewPasswordTableViewController.swift
  Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Extensions/Models/MessageExtensions.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Models/Message/MessageReply.swift
  Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
  Rocket.ChatTests/Models/MessageSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: 🐛 bug

#1673 [FIX] Sign up flow not completing
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/Clients/InfoClient.swift
  Rocket.Chat/API/Requests/User/UpdateUserRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/RegisterUsernameViewController.swift
  Rocket.Chat/Controllers/Auth/SignupViewController.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Labels: 🐛 bug

#1674 [FIX] Use other mapping from REST requests on "lastSeen" field
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: 🐛 bug

#1683 [IMPROVEMENT] Removed markdown from in-app notifications
  Rocket.Chat/Managers/NotificationManager.swift
Labels: 🎉 feature

#1685 [FIX] Infinite requesting API and empty userId for myself DMs
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/User/UserQueries.swift
  Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
Labels: 🐛 bug

#1699 [FIX] Some urls not receiving implicit https on connection
  Rocket.Chat/Extensions/URLExtension.swift
  Rocket.ChatTests/Extensions/URLExtensionSpec.swift
Labels: 🐛 bug, 👀 needs review

#1684 [FIX] API_Gitlab_Url setting not taking actual effect
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
  Rocket.Chat/Managers/OAuthManager.swift
Labels: 🐛 bug, 👀 needs review, 🔒 authentication

#1707 [FIX] Call completion block even on failures & errors
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Room/RoomsRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.ChatTests/API/Requests/Room/RoomsRequestSpec.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionsRequestSpec.swift
Labels: 🐛 bug

#1711 [FIX] Cell was not updating for reactors
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
Labels: 🐛 bug

#1712 [RELEASE] Merge develop into beta
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
Labels: 💎 release: beta

#1717 [IMPROVEMENT] Conform Attachments action sheet to new design
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
  Rocket.Chat/Extensions/UIAlertAction/UIAlertActionImage.swift
  Rocket.Chat/Extensions/UIAlertAction/UIAlertActionTitleTextAlignment.swift
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/AttachFiles.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/AttachFiles.imageset/files.pdf
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/ChooseFromLibrary.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/ChooseFromLibrary.imageset/library.pdf
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/DrawSomething.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/DrawSomething.imageset/newMessage.pdf
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/RecordVideo.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/RecordVideo.imageset/recordVideo.pdf
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/TakeAPhoto.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/TakeAPhoto.imageset/takeAPhoto.pdf
  Rocket.Chat/Resources/Assets.xcassets/Composer/Contents.json
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Labels: 👍 improvement, 🚸 ux

#1637 [NEW] Allow user with required permissions to remove member from room
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/APIRequest.swift
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Base/ResourceWithError.swift
  Rocket.Chat/API/Requests/Room/RoomCreateRequest.swift
  Rocket.Chat/API/Requests/Room/RoomFilesRequest.swift
  Rocket.Chat/API/Requests/Room/RoomInfoRequest.swift
  Rocket.Chat/API/Requests/Room/RoomKickRequest.swift
  Rocket.Chat/API/Requests/Room/RoomMembersRequest.swift
  Rocket.Chat/API/Requests/Room/RoomMentionsRequest.swift
  Rocket.Chat/API/Requests/Room/RoomMessagesRequest.swift
  Rocket.Chat/API/Requests/Room/RoomRolesRequest.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatControllerRolesController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerUserActionPresenter.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Controllers/Preferences/Language/LanguageViewController.swift
  Rocket.Chat/Controllers/Preferences/Language/LanguageViewModel.swift
  Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
  Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
  Rocket.Chat/Extensions/API/APIExtensions.swift
  Rocket.Chat/Helpers/Alert.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Models/Permission.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/User/UserPermissions.swift
  Rocket.Chat/Models/User/UserUtils.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Views/ActionSheets/UserActionSheetPresenter.swift
  Rocket.ChatTests/API/Clients/SubscriptionsClientSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomCreateRequestSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomFilesRequestSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomInfoRequestSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomKickRequestSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomMembersRequestSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomMentionsRequestSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomRolesRequestSpec.swift
  Rocket.ChatTests/Models/UserSpec.swift
Labels: 🎉 feature

#1716 [CHORE] Replace SDWebImage with Nuke
  Podfile
  Podfile.lock
  Rocket.Chat.ShareExtension/Base/SEAvatarView.swift
  Rocket.Chat.ShareExtension/Rooms/SERoomCell.swift
  Rocket.Chat.ShareExtension/Servers/SEServerCell.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/FilesListViewController.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiCollectionViewCell.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionView.swift
  Rocket.Chat/Managers/ImageManager.swift
  Rocket.Chat/Managers/Launcher/ImageCoordinator.swift
  Rocket.Chat/Managers/Launcher/LauncherProtocol.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageURLView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.Chat/Views/Cells/Subscription/ServerCell.swift
  Rocket.Chat/Views/Chat/RCTextView.swift
  Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift
Labels: 🚚 chore

#1728 [FIX] German translations
  Rocket.Chat/Resources/de.lproj/Localizable.strings
Labels: 🌎 i18n

#1729 [NEW] Autocomplete/Highlight should also happen for real names
  Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
  Rocket.Chat/Extensions/Models/UserExtensions.swift
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Extensions/StringExtensions.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Models/Mapping/MentionModelMapping.swift
  Rocket.Chat/Models/Message/Mention.swift
Labels: 🎉 feature

#1731 [NEW] New server selector
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Subscriptions/ServersViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsPageViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Helpers/Alert.swift
  Rocket.Chat/Managers/DatabaseManager.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Views/Cells/Subscription/ServerCell.swift
  Rocket.Chat/Views/Cells/Subscription/ServerCell.xib
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.xib
  Rocket.Chat/Views/Subscriptions/ServersListViewModel.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsTitleView.swift
  Rocket.ChatTests/Extensions/Models/UserExtensionsSpec.swift
  Rocket.ChatTests/Views/Subscriptions/ServersListViewModelSpec.swift
Labels: 🎉 feature

#1732 [FIX] Spotlight not working with new UI
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
Labels: 🐛 bug

#1734 [IMPROVEMENT] Removed whitespaces at the beginning of a message.
  Rocket.Chat/Extensions/Models/SubscriptionLastMessage.swift
Labels: 👍 improvement
