Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-08, with the labels that each got.

#2103 [I18N] Update all pt-BR strings for the notifications screen
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Labels: 🌎 i18n

#2101 [FIX] Background color for the search bar in EmojiPicker
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.xib
  Rocket.Chat/Theme/ThemeableViews.swift
Labels: 🌈 theme, 🚸 ux

#2105 [HOTFIX] Deeplink auth for servers without login services
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Info.plist
Labels: 💎 release: master, 🔥 hotfix

#2107 [DOCS] Update top header image & logo size
  README.md
Labels: 📝 docs

#2109 [FIX] Not taking server roles into account in room context
  Rocket.Chat/Models/User/UserPermissions.swift
Labels: 🐛 bug

#2106 [CHORE] Add events for "New Workspace" & "Status Update"
  Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/StatusTableViewController.swift
  Rocket.Chat/Managers/AnalyticsManager.swift
Labels: 🚚 chore

#2111 [RELEASE] Merge release 3.0.4 into MASTER
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/User/UserPermissions.swift
Labels: 💎 release: master

#2118 [FIX] Handle uploading images when there is no file size limit
  Rocket.Chat/Extensions/UIImageExtension.swift
Labels: 🐛 bug

#2128 [BUG] Quick reply adds new chat view
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/PushManager.swift
Labels: 🐛 bug

#2126 [BUG] It is not possible to change server
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🐛 bug

#2130 Update PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
Labels: 🐛 bug

#2139 [FIX] Message actions not taking into account room roles
  Rocket.Chat/Models/Auth/AuthCanDeleteMessage.swift
  Rocket.Chat/Models/Auth/AuthCanEditMessage.swift
  Rocket.Chat/Models/Auth/AuthCanPinMessage.swift
Labels: 🐛 bug, 👀 needs review, 🚸 ux

#2142 [IMPROVEMENT] Update UI optimistically after editing message
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
Labels: 🐛 bug, 👀 needs review, 👍 improvement

#2143 [FIX] Messages getting cut and scrolling
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Labels: 🐛 bug, 👀 needs review, 🚸 ux

#2136 [CRASH] Fatal Exception: RLMException Object has been deleted or invalidated
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Extensions/Models/ObjectExtension.swift
  Rocket.Chat/Managers/DraftMessageManager.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerTyping.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/Attachment.swift
  Rocket.Chat/Models/Base/BaseModel.swift
  Rocket.Chat/Models/User/UserUtils.swift
Labels: 👀 needs review, 💥 crash

#1960 [NEW] Add the actions to the Subscription (Hide, Leave, Mark as Read & Unread)
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionHideRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionLeaveRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionUnreadRequest.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
  Rocket.Chat/Extensions/DifferenceKitExtension.swift
  Rocket.Chat/Helpers/RealmAssorter.swift
  Rocket.Chat/Managers/AnalyticsManager.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/Subscription/UnmanagedSubscription.swift
  Rocket.Chat/Models/UnmanagedObject.swift
  Rocket.Chat/Models/User/UnmanagedUser.swift
  Rocket.Chat/Models/User/User.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe favorite.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe favorite.imageset/Swipe favorite.pdf
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe hide.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe hide.imageset/Swipe hide.pdf
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe read.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe read.imageset/Swipe read.pdf
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe unfavorite.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe unfavorite.imageset/Swipe unfavorite.pdf
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe unread.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Swipe Actions/Swipe unread.imageset/Swipe unread.pdf
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Sections/SubscriptionSectionView.xib
Labels: 🎉 feature, 👀 needs review

#2145 [NEW] Add Japanese translation file
  Rocket.Chat/Resources/ja.lproj/InfoPlist.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/VoiceOver.strings
Labels: 🌎 i18n

#2147 [I18N] Add Japanese to the Project
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/ja.lproj/RCEmojiKit.strings
Labels: 🌎 i18n

#1977 [NEW] Keyboard shortcuts
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Base/Main/MainSplitViewController.swift
  Rocket.Chat/Controllers/Base/Main/MainSplitViewControllerShortcuts.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
  Rocket.Chat/Helpers/ShortcutHelpers.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Theme/ThemeManager.swift
Labels: 🎉 feature, 🚨 needs changes

#2150 [I18N]Japanese translation file update
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
Labels: 🌎 i18n

#2144 [CHORE] Add script to validate localizable strings files
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Scripts/Localize.swift
Labels: 🚚 chore

#2151 [FIX] Fixed a crash on invalidated object, Japanese translation file & missing strings
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift
Labels: 🌎 i18n, 🐛 bug, 💥 crash

#2153 [HOTFIX] Fix not showing room selection when using shortcut
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🔥 hotfix

#2154 [CHORE] Add an event to when replying a notification
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Managers/AnalyticsManager.swift
  Rocket.Chat/Managers/PushManager.swift
Labels: 📊 analytics
