Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-02, with the labels that each got.

#1243 [NEW] Open DM when selecting user in Members List
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Managers/AppManager.swift
Labels: feature

#1240 [HOTFIX] Decrease maximum size of LaunchScreen image
  Rocket.Chat/Base.lproj/LaunchScreen.storyboard
Labels: hotfix

#1248 [CHORE] Small typo on the file header comments
  Rocket.Chat/API/Requests/Command/RunCommandRequest.swift
Labels: chore

#1249 [CHORE] Configure SwiftLint as pod and only in Debug
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Scripts/swiftlint.sh
Labels: chore

#1251 [IMPROVEMENT] Remove own typing indicator
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Managers/Model/AuthManager.swift
Labels: improvement

#1255 [NEW] Support SAML authentication
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Auth/SAMLViewController.swift
  Rocket.Chat/Managers/Model/AuthManager.swift
  Rocket.Chat/Models/LoginService.swift
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
Labels: feature

#1257 [NEW] Support post-readonly permission
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Models/Permission.swift
Labels: improvement

#1256 [FIX] Placeholder labels appearing when changing servers
  Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Managers/Model/AuthManager.swift
  Rocket.Chat/Models/Auth.swift
Labels: bug

#1262 [HOTFIX] Allow arbitrary loads for web content
  Rocket.Chat/Info.plist
Labels: hotfix

#1048 [NEW] Edit message
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Requests/Message/UpdateMessageRequest.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatControllerReplyHandler.swift
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Helpers/Alert.swift
  Rocket.Chat/Managers/Model/SubscriptionManager.swift
  Rocket.Chat/Models/Auth.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Permission.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Views/Chat/ReplyView.xib
  Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
  Rocket.ChatTests/Models/AuthSpec.swift
  Rocket.ChatTests/Models/MessageSpec.swift
Labels: feature

#1272 [FIX] Reaction size on iOS 10.x
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactionListView.xib
Labels: bug

#1274 [i18n] Remove unused localize string
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Labels: chore, i18n

#1275 [FIX] Application "loading for ever" if we try to connect to the server…
  Rocket.Chat/Managers/AppManager.swift
Labels: bug

#1273 [IMPROVEMENT] Prompt "App Store rating" after reacting to a message
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Managers/UserReviewManager.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Labels: app store, improvement

#1281 [FIX] User can block himself
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Models/Auth.swift
  Rocket.ChatTests/Models/AuthSpec.swift
Labels: bug

#1292 [FIX] Return key sending new message when editing
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
Labels: bug

#1293 [FIX] Crashing with certain messages with custom emojis
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
Labels: crash

#1297 [CHORE] Increment version to 2.0.1
  Rocket.Chat/Info.plist
Labels: chore

#1305 [FIX] Crash when displaying messages with duplicate custom emojis
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
Labels: crash

#1306 [IMPROVEMENT] Make spotlight case insensitive
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
Labels: improvement

#1294 [FIX] Not moving from register screen after registration
  Rocket.Chat/Controllers/Auth/SignupViewController.swift
Labels: bug

#1300 [FIX] Header in direct messages not displaying correctly sometimes
  Rocket.Chat/Models/User.swift
  Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
Labels: bug

#1304 [CI] Speed up the tests even more
  Scripts/build_for_testing.sh
  Scripts/test-11.0-ipad.sh
  Scripts/test-coverage.sh
  Scripts/test.sh
  Scripts/test_without_building.sh
  Scripts/test_without_building_coverage.sh
  circle.yml
Labels: ci

#1309 [CHORE] Increment version to 2.0.2
  Rocket.Chat/Info.plist
Labels: chore

#1324 [TESTS] Add SubscriptionExtensionsSpec
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: tests

#1218 [NEW] Support GitLab OAuth
  Rocket.Chat/Assets.xcassets/Icons/Auth/gitlab.imageset/Contents.json
  Rocket.Chat/Assets.xcassets/Icons/Auth/gitlab.imageset/gitlab@1x.png
  Rocket.Chat/Assets.xcassets/Icons/Auth/gitlab.imageset/gitlab@2x.png
  Rocket.Chat/Assets.xcassets/Icons/Auth/gitlab.imageset/gitlab@3x.png
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/LoginService.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/gitlab.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/gitlab.imageset/gitlab@1x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/gitlab.imageset/gitlab@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/gitlab.imageset/gitlab@3x.png
  Rocket.ChatTests/Models/LoginServiceSpec.swift
Labels: feature

#1311 [RELEASE] Merge beta into master
  Rocket.Chat/Controllers/Auth/SignupViewController.swift
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/User.swift
  Rocket.Chat/Views/Cells/Chat/ChatDirectMessageHeaderCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
  Scripts/build_for_testing.sh
  Scripts/install_swiftlint.sh
  Scripts/test-10.3-ipad.sh
  Scripts/test-11.0-ipad.sh
  Scripts/test-11.0-iphone.sh
  Scripts/test_without_building.sh
  Scripts/test_without_building_coverage.sh
  Scripts/update_dependencies.sh
  circle.yml
Labels: release:master

#1323 [FIX] Call super on viewDidLoad to load all tintColor settings
  Rocket.Chat/SettingsNavigationController.swift
Labels: bug

#1321 [CHORE] Update most of our Pods
  Podfile.lock
Labels: libraries:updates

#1336 [I18N] Improve French translation
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
Labels: i18n

#1334 [FIX] Remove description indicator
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageAudioView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageAudioView.xib
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.xib
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.xib
Labels: bug

#1348 [FIX] Channels searching case insensitive
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
Labels: improvement

#1343 [IMPROVEMENT] Make users searching in create new room (inviting user) case and diacritic insensitive
  Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.swift
Labels: improvement

#1325 [IMPROVEMENT] Update order of items in "Preferences" & title in menu
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Settings/PreferencesNavigationController.swift
  Rocket.Chat/Controllers/Settings/PreferencesViewController.swift
  Rocket.Chat/Controllers/Settings/PreferencesViewModel.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionUserStatusView.xib
  Rocket.ChatTests/Settings/PreferencesViewModelSpec.swift
Labels: improvement

#1270 [NEW] Support for offline messages
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatControllerSocketConnectionHandler.swift
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Helpers/MessageTextFontAttributes.swift
  Rocket.Chat/Models/Base/BaseModel.swift
  Rocket.Chat/Models/Message.swift
  Rocket.Chat/Models/Subscription.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Clock.imageset/Clock.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Clock.imageset/Clock@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Clock.imageset/Clock@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Clock.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Exclamation.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Exclamation.imageset/Exclamation.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Exclamation.imageset/Exclamation@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Exclamation.imageset/Exclamation@3x.png
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
  Rocket.ChatTests/Models/BaseModelSpec.swift
  Rocket.ChatTests/Models/MessageSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: feature

#1329 [NEW] Add "new messages" separator between old and new messages
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Chat/ChatMessageDaySeparator.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageDaySeparator.xib
  Rocket.Chat/Views/Cells/Chat/ChatMessageUnreadSeparator.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageUnreadSeparator.xib
  Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift
Labels: feature

#1332 [NEW] Add support to named colors, remove new lines on title from bots
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Extensions/StringExtensions.swift
  Rocket.Chat/Extensions/UIColorExtension.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextViewModel.swift
  Rocket.ChatTests/Extensions/StringExtensionSpec.swift
  Rocket.ChatTests/Extensions/UIColorExtensionSpec.swift
Labels: feature, improvement

#1356 [I18N] Add Greek Localization
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/el.lproj/RCEmojiKit.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/VoiceOver.strings
Labels: i18n

#1250 [NEW] Add option to draw something and send
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
  Rocket.Chat/Controllers/Drawing/DrawingBrushColorViewController.swift
  Rocket.Chat/Controllers/Drawing/DrawingBrushOpacityViewController.swift
  Rocket.Chat/Controllers/Drawing/DrawingBrushWidthViewController.swift
  Rocket.Chat/Controllers/Drawing/DrawingControllerDelegate.swift
  Rocket.Chat/Drawing.storyboard
  Rocket.Chat/DrawingBrushColorViewModel.swift
  Rocket.Chat/DrawingViewController.swift
  Rocket.Chat/DrawingViewModel.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Color.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Color.imageset/color.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Color.imageset/color@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Color.imageset/color@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Opacity.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Opacity.imageset/opacity.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Opacity.imageset/opacity@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Opacity.imageset/opacity@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Reset.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Reset.imageset/trash.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Reset.imageset/trash@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Reset.imageset/trash@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Width.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Width.imageset/size.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Width.imageset/size@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Drawing/Width.imageset/size@3x.png
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Views/ColorPicker/ColorPickerView.swift
  Rocket.ChatTests/Models/DrawingBrushColorSpec.swift
  Rocket.ChatTests/Models/DrawingViewModelSpec.swift
Labels: feature

#1303 [IMPROVEMENT] Don't display emojis inside code blocks
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/Emojione.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.ChatTests/External/RCEmojiKit/EmojioneSpec.swift
Labels: improvement

#1361 [I18N] Add Spanish language
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/es.lproj/RCEmojiKit.strings
  Rocket.Chat/Info.plist
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/VoiceOver.strings
Labels: i18n
