Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-06, with the labels that each got.

#1733 [IMPROVEMENT] Initial steps to the rewrite of "New Message/Channel" flow
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
  Rocket.Chat/Storyboards/New Room.storyboard
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Views/Form/Cells/CheckTableViewCell.swift
  Rocket.Chat/Views/Form/Cells/CheckTableViewCell.xib
  Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.swift
  Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.xib
  Rocket.Chat/Views/Form/Cells/TextFieldTableViewCell.swift
  Rocket.Chat/Views/Form/Cells/TextFieldTableViewCell.xib
  Rocket.Chat/Views/Form/FormTableViewCell.swift
  Rocket.ChatTests/Views/CreateChannel/MentionsTextFieldTableViewCellSpec.swift
Labels: 👍 improvement, 🚚 chore

#1742 [FIX] Added a space before the "sent an attachment" text
  Rocket.Chat/Extensions/Models/SubscriptionLastMessage.swift
Labels: 🐛 bug

#1744 [NEW] Russian translation file
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/VoiceOver.strings
Labels: 🌎 i18n

#1743 [FIX] Fix weird scrolling behavior on Subscriptions VC
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/DrawSomething.imageset/Contents.json
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
Labels: 🐛 bug, 👍 improvement

#1745 [FIX] Project adjustments to support Russian language properly
  Rocket.Chat.xcodeproj/project.pbxproj
Labels: 🌎 i18n

#1746 [FIX] Update RU Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🌎 i18n

#1748 [FIX] Tests fixed
  Rocket.ChatTests/API/Clients/SubscriptionsClientSpec.swift
  Rocket.ChatTests/Controllers/NotificationViewControllerSpec.swift
  Rocket.ChatTests/Extensions/Models/UserExtensionsSpec.swift
  Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift
Labels: ✅ tests

#1751 [FIX] Fix server list view frame on iOS 10
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
Labels: 🐛 bug

#1750 [HOTFIX] Fix for web browser preference getting hidden instead of the app icon preference if the device does not support changing app icons.
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Storyboards/Preferences.storyboard
Labels: 🐛 bug

#1756 [NEW] Add Administration and Logout to Preferences screen
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewModel.swift
  Rocket.Chat/Controllers/Preferences/Profile/StatusViewModel.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.ChatTests/Preferences/PreferencesViewModelSpec.swift
Labels: 🎉 feature, 👀 needs review

#1758 [CHORE] Remove unused files from the filesystem
  Rocket.Chat/Models/Auth.swift
  Rocket.Chat/Models/Subscription.swift
  Rocket.Chat/Models/User.swift
Labels: 👀 needs review, 🚚 chore

#1757 [NEW] Allow the user to share the room link with others
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
  Rocket.Chat/Extensions/StringExtensions.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
  Rocket.ChatTests/Extensions/StringExtensionSpec.swift
  Rocket.ChatTests/Models/AuthSettingsSpec.swift
Labels: 🎉 feature, 👀 needs review

#1753 [NEW] WebSocket connection status on the title view
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerConnectionHandler.swift
  Rocket.Chat/Controllers/Base/MainSplitViewController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Managers/LogManager.swift
  Rocket.Chat/Managers/NetworkManager.swift
  Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Chat/ChatTitleView.swift
  Rocket.Chat/Views/Chat/ChatTitleView.xib
  Rocket.Chat/Views/Subscriptions/SubscriptionsTitleView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsTitleView.xib
  Rocket.ChatTests/Managers/Socket/SocketManagerConnectionHandlerSpec.swift
  Rocket.ChatTests/Views/Chat/ChatTitleViewSpec.swift
  Rocket.ChatTests/Views/Subscriptions/SubscriptionsTitleViewSpec.swift
Labels: 👀 needs review, 👍 improvement

#1754 [NEW] Support message read receipt
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/API/Requests/Message/ReadReceiptsRequest.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Mapping/MessageModelMapping.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check.imageset/Check.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check.imageset/Check@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check.imageset/Check@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check.imageset/Contents.json
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
  Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListView.swift
  Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListView.xib
  Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListViewController.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
  Rocket.ChatTests/API/Requests/Message/ReadReceiptsRequestSpec.swift
Labels: 🎉 feature, 👀 needs review

#1768 [FIX] Close serversView and sortingView on SubscriptionsVC when search bar is tapped
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Labels: 🐛 bug

#1771 [IMPROVEMENTS] Subscriptions & Rooms request improvements & bug fixes
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Labels: 🐛 bug, 👍 improvement

#1770 [NEW] Add Topic, Description & Name of the channel on action controller and improve accessibility
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileViewModel.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoActionCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoActionCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDetailCell.swift
Labels: 🎉 feature

#1773 [RELEASE] Merge BETA into MASTER
  Podfile.lock
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/API/Requests/Message/ReadReceiptsRequest.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Mapping/MessageModelMapping.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check.imageset/Check.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check.imageset/Check@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check.imageset/Check@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Check.imageset/Contents.json
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
  Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListView.swift
  Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListView.xib
  Rocket.Chat/Views/Cells/Chat/ReadReceipts/ReadReceiptListViewController.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
  Rocket.ChatTests/API/Requests/Message/ReadReceiptsRequestSpec.swift
Labels: 💎 release: master

#1774 [IMPROVEMENT] Add support to custom fields on Sign up
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Controllers/Auth/SignupCustomFieldsTableViewController.swift
  Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
  Rocket.Chat/Controllers/Auth/SignupViewControllerCustomFields.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.Chat/Views/Cells/Auth/CustomFieldTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/CustomFieldTableViewCell.xib
Labels: 👀 needs review, 👍 improvement

#1785 [IMPROVEMENT] Improvements in Russian translation
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🌎 i18n

#1782 [BUG][NEW ONBOARDING] Cannot login using 2FA on
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Labels: 🐛 bug, 👀 needs review

#1783 [CRASH] 2FA auth crashing when popped
  Rocket.Chat/Controllers/Auth/AuthTableViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewControllerAuthenticationHandler.swift
Labels: 👀 needs review, 💥 crash

#1787 [NEW] Translate ger 3.0
  Rocket.Chat/Helpers/Alert.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Preferences.storyboard
Labels: 🌎 i18n

#1790 [FIX] Not being able to close images or videos in iPhone X
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
Labels: 🐛 bug

#1791 [BUG] Authenticating without username
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
  Rocket.Chat/Managers/WindowManager.swift
  Rocket.Chat/Storyboards/Auth.storyboard
Labels: 🐛 bug

#1793 [IMPROVEMENT][NEW ONBOARDING] Update en strings according to suggestions
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.ChatTests/Managers/ServerManagerSpec.swift
Labels: 👀 needs review, 👍 improvement

#1795 [IMPROVEMENT] Some UI adjustments for iPad
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.Chat/Views/Cells/Auth/AuthSeparatorTableViewCell.xib
  Rocket.Chat/Views/Cells/Auth/CustomFieldTableViewCell.xib
  Rocket.Chat/Views/Cells/Auth/EmailAuthTableViewCell.xib
  Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.xib
  Rocket.Chat/Views/Cells/Auth/ShowMoreSeparatorTableViewCell.xib
Labels: 👍 improvement

#1798 [BUG] Resolve issue on breaking the cell layout for new messages on loading history
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
Labels: 🐛 bug

#1778 [IMPROVEMENTS] Couple of UI adjustments for the new layout
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40@3x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60@3x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-72.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-72@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-83.5@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small-50.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small-50@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small@3x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/NotificationIcon@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/NotificationIcon@3x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/NotificationIcon~ipad.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/NotificationIcon~ipad@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoActionCell.xib
  Rocket.Chat/Views/Cells/Subscription/ServerCell.swift
  Rocket.Chat/Views/Cells/Subscription/ServerCell.xib
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Chat/ChatTitleView.xib
  Rocket.Chat/Views/Subscriptions/SubscriptionsTitleView.xib
Labels: 👍 improvement, 🖼 layout

#1800 [IMPROVEMENT] Resolve strong retain cycle on SubscriptionViewController
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
Labels: 👀 needs review, 👍 improvement

#1797 [IMPROVEMENT][THEME] Use the new colors for the dark theme
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Preferences/ChangeAppIcon/ChangeAppIconViewController.swift
  Rocket.Chat/Controllers/Subscriptions/AudioFileViewController.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Theme/Theme.swift
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Loader/LoaderView.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingSeparatorView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
Labels: 🖼 layout

#1802 [IMPROVEMENTS] Many UI improvements and i18n support on actions
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoActionCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.xib
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Labels: 👍 improvement

#1804 [BUG] Sometimes set username screen appears when opening the app when username is already set
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
Labels: 🐛 bug

#1811 [IMPROVEMENT] Improvements in Russian translation
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🌎 i18n

#1808 [I18N] Added Greek translations
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
Labels: 🌎 i18n

#1813 [IMPROVEMENT] Fix some memory related issues
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/Middlewares/VersionMiddleware.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.Chat/Views/Base/BaseNavigationBar.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/ServersListViewModel.swift
Labels: 👀 needs review, 👍 improvement

#1816 [CHORE] Couple improvements on the API requests & UI
  Rocket.Chat/API/Clients/AuthClient.swift
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Room/RoomsRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerRecover.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Models/Auth/Auth.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.ChatTests/Controllers/ChatDataControllerSpec.swift
Labels: 🐛 bug, 👍 improvement, 📡 networking

#1825 [i18n] Add polish translation for new strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
Labels: 🌎 i18n

#1822 [FIX] Transparent nav bar and reactors list headers
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Auth/AuthNavigationController.swift
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/LegalTableViewController.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
  Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
  Rocket.Chat/Controllers/Base/BaseNavigationController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.Chat/Theme/ThemeableViews.swift
Labels: 🐛 bug

#1828 [CRASH] Our users are experiencing random crashes when logging out
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Labels: 💥 crash

#1834 [IMPROVEMENT] Improvements in Russian translation
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🌎 i18n

#1833 [IMPROVEMENT] Fallback to websocket when registering username and fix a bug related to websocket authentication
  Rocket.Chat/API/Clients/AuthClient.swift
  Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
  Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Labels: 👍 improvement

#1824 [CI] use correct gems versions
  Gemfile
  Gemfile.lock
  Scripts/before_install.sh
  Scripts/update_dependencies.sh
  circle.yml
Labels: 👷 ci

#1809 [IMPROVEMENT] Refactor SubscriptionsViewController
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/SpotlightClient.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
  Rocket.Chat/Helpers/RealmAssorter.swift
  Rocket.Chat/Models/Handler/UserModelHandler.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Labels: 👍 improvement, 🚨 needs changes
