Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-07, with the labels that each got.

#1849 [NEW] Improve analytics logging
  .gitignore
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Auth/AuthTableViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/CASViewController.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/SAMLViewController.swift
  Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
  Rocket.Chat/Controllers/Base/BaseTableViewController.swift
  Rocket.Chat/Controllers/Base/BaseViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Drawing/DrawingBrushColorViewController.swift
  Rocket.Chat/Controllers/Drawing/DrawingBrushOpacityViewController.swift
  Rocket.Chat/Controllers/Drawing/DrawingBrushWidthViewController.swift
  Rocket.Chat/Controllers/Drawing/DrawingViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewModel.swift
  Rocket.Chat/Controllers/Preferences/Theme/ThemePreferenceController.swift
  Rocket.Chat/Controllers/Preferences/Web Browser/WebBrowserTableViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Managers/AnalyticsManager.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Launcher/AnalyticsCoordinator.swift
  Rocket.Chat/Managers/Launcher/LauncherProtocol.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
Labels: 👀 needs review, 🚚 chore

#1846 [FIX] Emoji avatars disappearing after a second
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Labels: 🐛 bug

#1835 [IMPROVEMENT] Improve image compression
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Extensions/DataExtension.swift
  Rocket.Chat/Extensions/UIImageExtension.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
Labels: 👍 improvement

#1854 Portuguese (PT) translation
  Rocket.Chat.ShareExtension/Resources/pt-PT.lproj/Localizable.strings
Labels: 🌎 i18n

#1853 Create Portuguese (Portugal) language
  Rocket.Chat.ShareExtension/Resources/pt-PT.lproj/Localizable.strings
Labels: 🌎 i18n

#1864 [I18N] Finalize pt-PT integration
  Rocket.Chat.ShareExtension/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/pt-PT.lproj/RCEmojiKit.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/VoiceOver.strings
  Rocket.Chat/Storyboards/Subscriptions.storyboard
Labels: 🌎 i18n

#1873 [BUG] App crashes upon clicking +Create a new workspace
  Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
Labels: 💥 crash

#1872 [FIX] Tests
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.ChatTests/Managers/Launcher/BugTrackingCoordinatorSpec.swift
  Rocket.ChatTests/Preferences/PreferencesViewModelSpec.swift
Labels: 🚚 chore

#1850 [IMPROVEMENT] Allow setting theme properties through User Defined Runtime Attributes
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
  Rocket.Chat/Controllers/Preferences/PreferencesViewModel.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Theme/RuntimeAttributesThemeableView.swift
  Rocket.Chat/Theme/Theme.swift
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.ChatTests/Managers/Launcher/AnalyticsCoordinatorSpec.swift
  Rocket.ChatTests/Theme/RuntimeAttributesThemeableViewSpec.swift
  Rocket.ChatTests/Theme/ThemeManagerSpec.swift
  Rocket.ChatTests/Theme/ThemeableSpec.swift
Labels: 🎉 feature

#1875 [IMPROVEMENT] Improvements in Russian translation
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🌎 i18n

#1870 [BUG] Profile picture didn't change
  Podfile
  Podfile.lock
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Managers/ImageManager.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
Labels: 🐛 bug

#1867 [BUG] Channel deep links not working
  Rocket.Chat/Views/Chat/RCTextView.swift
Labels: 🐛 bug

#1878 [FIX] Rotation related issues on onboarding flow
  Rocket.Chat/Controllers/Auth/AuthNavigationController.swift
Labels: 🐛 bug

#1876 [CHORE] Remove unused files
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerHeaderStatus.swift
  Rocket.Chat/Controllers/Chat/ChatControllerSocketConnectionHandler.swift
  Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Labels: 🚚 chore

#1837 [NEW] User details screen
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Clients/UsersClient.swift
  Rocket.Chat/Controllers/Base/BaseNavigationController.swift
  Rocket.Chat/Controllers/Base/BaseViewController.swift
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileViewModel.swift
  Rocket.Chat/Controllers/User/UserDetail/Cell/UserDetailFieldCell.swift
  Rocket.Chat/Controllers/User/UserDetail/Cell/UserDetailFieldCellModel.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetail.storyboard
  Rocket.Chat/Controllers/User/UserDetail/UserDetailHeaderView.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetailTableView.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetailViewModel.swift
  Rocket.Chat/Extensions/DateExtension.swift
  Rocket.Chat/Extensions/UIButton/UIButtonCenterImage.swift
  Rocket.Chat/Extensions/UINavigationBar/UINavigationBarTransparent.swift
  Rocket.Chat/Extensions/UINavigationController/UINavigationControllerExtension.swift
  Rocket.Chat/Extensions/UINavigationController/UINavigationControllerRedrawBar.swift
  Rocket.Chat/Extensions/UIViewController/UIViewControllerPushOrPresent.swift
  Rocket.Chat/Helpers/StoryboardInitializable.swift
  Rocket.Chat/Models/User/User.swift
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/UserDetail_Message.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/UserDetail_Message.imageset/messageDark.pdf
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/UserDetail_VideoCall.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/UserDetail_VideoCall.imageset/videoGrey.pdf
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/UserDetail_VoiceCall.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/UserDetail_VoiceCall.imageset/phoneDark.pdf
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/Victoria_Anderson.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/UserDetail/Victoria_Anderson.imageset/gbhtKFSgTuZF11RzYNdv_240.jpg
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/ActionSheets/UserActionSheetPresenter.swift
Labels: 🎉 feature

#1881 [FIX] Table view cells getting incorrectly themed
  Rocket.Chat/Theme/ThemeableViews.swift
Labels: 🐛 bug

#1880 [IMPROVEMENT] Login Page > "Create an Account" should stay in place when the keyboard is hidden
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Storyboards/Auth.storyboard
Labels: 👍 improvement

#1884 [FIX] Channel description becomes smaller with longer length
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoActionCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoCellProtocol.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoUserCell.swift
Labels: 🐛 bug

#1885 [IMPROVEMENT] Tappable subscriptions sorting view
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Icon Filter.imageset/Contents.json
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.xib
Labels: 👍 improvement

#1886 [FIX] Incorrectly sorting when "UI_Use_Real_Name" is activated
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
Labels: 🐛 bug

#1888 [BUG] Subscriptions list is empy when first joining a server
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
Labels: 🐛 bug

#1899 [FIX] Text input bar not moving to the bottom of the screen.
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
Labels: 🐛 bug, 🖼 layout

#1905 [BUG] Chat page > Three-Dot menu > Members > Members modal stays open after selecting Message
  Rocket.Chat/Managers/AppManager.swift
Labels: 🐛 bug

#1904 [IMPROVEMENT] Join the Community > Create new account > Register button keeps loading when registering with null password
  Rocket.Chat/Controllers/Auth/SignupTableViewController.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🐛 bug

#1901 [BUG] Letting the user logout from all servers on server list
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
Labels: 🐛 bug

#1907 [IMPROVEMENT] Improve message sent events and add some user properties
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Managers/AnalyticsManager.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManager.swift
Labels: 👍 improvement

#1908 [BUG] Adjust unread margins for iPads on missing Outlets connections
  Rocket.Chat/Storyboards/Subscriptions.storyboard
Labels: 🐛 bug

#1918 [I18N] Updated French Localization for 3.0.0
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
Labels: 🌎 i18n

#1916 [IMPROVEMENT] Restrict Channel name to a certain number of characters
  Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
  Rocket.Chat/Views/Form/Cells/TextFieldTableViewCell.swift
  Rocket.Chat/Views/Form/FormTableViewCell.swift
Labels: 👍 improvement

#1919 [I18N] Updated French Localization for 3.0.0 Share Extension
  Rocket.Chat.ShareExtension/Resources/fr.lproj/Localizable.strings
Labels: 🌎 i18n

#1926 [CRASH] Crashing when trying to open an URL from UITextView
  Rocket.Chat/Views/Chat/RCTextView.swift
Labels: 💥 crash

#1929 [FIX] Custom OAuth not working if Authorize Path is full URL
  Rocket.Chat/Models/LoginService.swift
Labels: 🐛 bug, 🔒 authentication

#1934 [IMPROVEMENT] Theming performance improvement in SubscriptionCell
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCellCondensed.swift
Labels: 👍 improvement, 🚀 performance

#1933 [CHORE] Performance improvements & couple of improvements
  Rocket.Chat/API/Clients/CommandsClient.swift
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/Extensions/Models/UserExtensions.swift
Labels: 👍 improvement, 🚀 performance, 🚚 chore

#1930 [FIX] Attachment coloring does not work
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextViewModel.swift
  Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift
Labels: 🐛 bug

#1928 [FIX] Minor theming issues
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.swift
  Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.xib
Labels: 👍 improvement, 🚸 ux

#1887 [IMPROVEMENT] Reduce tappable area for sorting header view
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Views/Subscriptions/SubscriptionsTitleView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsTitleView.xib
Labels: 👍 improvement

#1889 [NEW] Upload status banner
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/UploadClient.swift
  Rocket.Chat/Controllers/Chat/ChatControllerDocuments.swift
  Rocket.Chat/Controllers/Chat/ChatControllerUploader.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Chat/ChatViewControllerBanner.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Resources/Assets.xcassets/Message/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Cancel.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Cancel.imageset/cancel.pdf
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Error.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Error.imageset/error.pdf
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_File.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_File.imageset/filesGrey.pdf
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Image.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Image.imageset/libraryGrey.pdf
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerView.swift
  Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerView.xib
  Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerViewModel.swift
  Rocket.Chat/Views/Chat/ChatHeaderViewStatus.swift
  Rocket.Chat/Views/Chat/ChatHeaderViewStatus.xib
Labels: 🎉 feature

#1940 [FIX] Crash due to in-app notifications
  Rocket.Chat/Managers/NotificationManager.swift
  Rocket.Chat/Models/ChatNotification.swift
  Rocket.ChatTests/Managers/NotificationManagerSpec.swift
  Rocket.ChatTests/Models/ChatNotificationSpec.swift
Labels: 🐛 bug, 💥 crash

#1935 [BUG] Attempt to fix a database inconsistency and some minor improvements on the server switching process
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Extensions/API/APIExtensions.swift
  Rocket.Chat/Managers/Model/CustomEmojiManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.ChatTests/Extensions/API/APIExtensionsSpec.swift
Labels: 🐛 bug

#1947 [FIX] Navigation Bar transparent after going to DM via User Detail
  Rocket.Chat/Controllers/Base/BaseNavigationController.swift
  Rocket.Chat/Controllers/Base/BaseViewController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
Labels: 🐛 bug

#1941 [IMPROVEMENT] In app notification now support multiple lines of text
  Rocket.Chat/Controllers/Notification/NotificationViewController.swift
  Rocket.Chat/Controllers/Notification/NotificationViewController.xib
  Rocket.Chat/Views/Notification/NotificationView.swift
Labels: 👍 improvement

#1944 [IMPROVEMENT] Theme upload banner
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Cancel.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_File.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Image.imageset/Contents.json
  Rocket.Chat/Theme/Theme.swift
  Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerView.swift
  Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerView.xib
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
Labels: 👍 improvement

#1946 [FEATURE] Add Home Screen Quick Actions
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/ShortcutsManager.swift
  Rocket.Chat/Resources/cs.lproj/InfoPlist.strings
  Rocket.Chat/Resources/de.lproj/InfoPlist.strings
  Rocket.Chat/Resources/el.lproj/InfoPlist.strings
  Rocket.Chat/Resources/en.lproj/InfoPlist.strings
  Rocket.Chat/Resources/es.lproj/InfoPlist.strings
  Rocket.Chat/Resources/fr.lproj/InfoPlist.strings
  Rocket.Chat/Resources/pl.lproj/InfoPlist.strings
  Rocket.Chat/Resources/pt-BR.lproj/InfoPlist.strings
  Rocket.Chat/Resources/pt-PT.lproj/InfoPlist.strings
  Rocket.Chat/Resources/ru.lproj/InfoPlist.strings
  Rocket.ChatTests/Managers/ShortcutsManagerSpec.swift
Labels: 🎉 feature

#1942 [CHORE] Remove the object lookups on Realm updates & increase a lot the performance of the app
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
  Rocket.Chat/Helpers/RealmAssorter.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/NotificationManager.swift
  Rocket.Chat/Models/ChatNotification.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.ChatTests/Managers/NotificationManagerSpec.swift
  Rocket.ChatTests/Models/ChatNotificationSpec.swift
Labels: 🚀 performance, 🚚 chore

#1938 [NEW] Add 3D Touch interaction to the Subscriptions List
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🎉 feature

#1945 [FIX] Crash when trying to share a room on an iPad
  Rocket.Chat/Controllers/Auth/AuthTableViewControllerLoginServices.swift
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
Labels: 💥 crash

#1949 [CHORE] Update AppIcon & LaunchScreen
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-40@3x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-60@3x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-72.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-72@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-76@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-83.5@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small-50.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small-50@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon-Small@3x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/Icon@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/NotificationIcon@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/NotificationIcon@3x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/NotificationIcon~ipad.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/NotificationIcon~ipad@2x.png
  Rocket.Chat/Resources/Assets.xcassets/AppIcon.appiconset/ios-marketing.png
  Rocket.Chat/Resources/Assets.xcassets/Launch Screen Icon.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Launch Screen Icon.imageset/Icon-1.png
  Rocket.Chat/Resources/Assets.xcassets/Launch Screen Icon.imageset/icon.png
  Rocket.Chat/Resources/Assets.xcassets/Launch Screen Icon.imageset/icon@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Launch Screen Icon.imageset/icon@3x.png
  Rocket.Chat/Storyboards/Base.lproj/LaunchScreen.storyboard
Labels: 🖼 layout

#1943 [IMPROVEMENT] Theme scroll to bottom indicator
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button black.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button black.imageset/floatButtonDarkmode.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button black.imageset/floatButtonDarkmode@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button black.imageset/floatButtonDarkmode@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button dark.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button dark.imageset/floatButtonDarkmodeCopy2.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button dark.imageset/floatButtonDarkmodeCopy2@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button dark.imageset/floatButtonDarkmodeCopy2@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button light.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button light.imageset/Float Button.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button light.imageset/Float Button@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Chat/Float Button light.imageset/Float Button@3x.png
Labels: 👍 improvement

#1950 [FIX] Star glyph now gets themed appropriately
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Star-Filled.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Star.imageset/Contents.json
Labels: 🐛 bug

#1958 [TESTS] Fixed all breaking tests and add a new one for hidden rooms
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.ChatTests/Extensions/API/APIExtensionsSpec.swift
  Rocket.ChatTests/Extensions/Models/SubscriptionExtensionsSpec.swift
  Rocket.ChatTests/Helpers/UploadHelperSpec.swift
  Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: ✅ tests

#1955 [FIX] Crash on toggling Crash Reports & remove Instabug (not being used)
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Managers/Launcher/AnalyticsCoordinator.swift
Labels: 🐛 bug, 💥 crash, 🚚 chore

#1956 [FIX] Race condition on first user, iOS 11 optimization on the list & update titleView for Subscription updates
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Labels: 🐛 bug, 🚚 chore

#1957 [FIX] App not refreshing messages when opening from notification or changing network status
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🐛 bug

#1961 [CHORE] Update some of the Pods
  Podfile.lock
Labels: 🚚 chore

#1963 [CRASH] Avoid getting the wrong thread on user status updates
  Rocket.Chat/Extensions/Models/UserExtensions.swift
Labels: 💥 crash

#1966 [I18N] Updated German Localization for 3.0.0
  Rocket.Chat/Resources/de.lproj/InfoPlist.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/VoiceOver.strings
Labels: 🌎 i18n

#1967 [FIX] Theming on swipe actions
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Theme/ThemeableViews.swift
Labels: 🐛 bug

#1965 [i18n] Localize usage (permission) descriptions from Info.plist file
  Rocket.Chat/Info.plist
  Rocket.Chat/Resources/cs.lproj/InfoPlist.strings
  Rocket.Chat/Resources/de.lproj/InfoPlist.strings
  Rocket.Chat/Resources/el.lproj/InfoPlist.strings
  Rocket.Chat/Resources/en.lproj/InfoPlist.strings
  Rocket.Chat/Resources/es.lproj/InfoPlist.strings
  Rocket.Chat/Resources/fr.lproj/InfoPlist.strings
  Rocket.Chat/Resources/pl.lproj/InfoPlist.strings
  Rocket.Chat/Resources/pt-BR.lproj/InfoPlist.strings
  Rocket.Chat/Resources/pt-PT.lproj/InfoPlist.strings
  Rocket.Chat/Resources/ru.lproj/InfoPlist.strings
Labels: 🌎 i18n

#1969 [CRASH] Join a new room, create a new DM and more
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/SpotlightClient.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerSearch.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
  Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.swift
Labels: 🐛 bug, 💥 crash

#1971 [FIX] Resolve sorting problem when fname property is empty and is sorting by it
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
Labels: 🐛 bug

#1970 [FIX] Cell reutilization sizes on rotate & indexPath position
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
Labels: 🐛 bug

#1973 [FIX] Adjust subscriptions list according to keyboard's frame
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🐛 bug

#1974 [BUG] Deeplink auth not working properly
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/WindowManager.swift
Labels: 🐛 bug

#1978 [NEW] Add empty state to the right side of the chat
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Managers/ShortcutsManager.swift
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State black.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State black.imageset/Message Empty Black Theme.pdf
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State dark.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State dark.imageset/Message Empty Dark Theme.pdf
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State light.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State light.imageset/Message Empty.pdf
Labels: 🖼 layout

#1976 [CHORE] Adjust recent changes made to SpotlightClient and fix tests
  Rocket.Chat/API/Clients/SpotlightClient.swift
  Rocket.ChatTests/API/Clients/SpotlightClientSpec.swift
Labels: 🚚 chore

#1980 [I18N] Update greek translations for 3.0.0
  Rocket.Chat.ShareExtension/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/InfoPlist.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
Labels: 🌎 i18n

#1981 [FIX] Flickering tableview cells on iPad
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🚸 ux

#1984 [FIX] Use transparent navigationBar on the Onboarding screens
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/WelcomeViewController.swift
Labels: 🐛 bug

#1985 [BUX] Fix clipped application icon's border on changing icon screen
  Rocket.Chat/Storyboards/Preferences.storyboard
Labels: 🐛 bug

#1992 [BUG] Reduce the amount of time to ~28 hours instead of the same second
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Labels: 🐛 bug

#1995 [CHORE] Use ISO formatter & encode the string before sending it to the URL
  Rocket.Chat/API/Requests/Room/RoomsRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
Labels: 🐛 bug

#1990 [CRASH] Fatal Exception: NSInternalInconsistencyException Only run on the main thread!
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Labels: 💥 crash

#1994 [FIX] Server isolation issues
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/DatabaseManager.swift
Labels: 🐛 bug

#1997 [FIX] Share extension missing reference compile error
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Managers/DatabaseManager.swift
  Rocket.Chat/Managers/DatabaseManagerAuthSettings.swift
Labels: 🚚 chore

#1996 [FIX] Invalid session support
  Rocket.Chat/Managers/Socket/Response/SocketError.swift
  Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
Labels: 👍 improvement

#1998 [RELEASE] Merge DEVELOP into BETA
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Room/RoomsRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/DatabaseManager.swift
  Rocket.Chat/Managers/DatabaseManagerAuthSettings.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/Socket/Response/SocketError.swift
  Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
Labels: 💎 release: beta

#2002 [CRASH] Fatal Exception: NSInternalInconsistencyException -[UIKeyboardTaskQueue waitUntilAllTasksAreFinished] may only be called from the main thread.
  Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
Labels: 💥 crash

#2004 [CHORE] Increment app version to 3.0.1
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
Labels: 🚚 chore

#2010 [CRASH] Subscription to deleted messages
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Info.plist
Labels: 💥 crash

#2013 [BUG] Replace deprecated method and fix interaction with deep press
  Rocket.Chat/Views/Chat/RCTextView.swift
Labels: 🐛 bug

#2005 [RELEASE] Merge DEVELOP into MASTER
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Views/Chat/RCTextView.swift
Labels: 💎 release: master

#2021 [IMPROVEMENT] UserDetail popover sizing on iPad
  Rocket.Chat/Controllers/User/UserDetail/UserDetailTableView.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
Labels: 👍 improvement, 🚸 ux

#1999 [HOTFIX] Search bar clear button not hiding
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🔥 hotfix, 🖼 layout

#2017 [REFACTOR] SubscriptionCell and SubscriptionCellCondensed
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCellCondensed.swift
Labels: ♻️ refactor

#1932 [CHORE] Reducing warnings and refactoring
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Clients/SpotlightClient.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetail.storyboard
  Rocket.Chat/Extensions/UIButton/UIButtonCenterImage.swift
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Theme/RuntimeAttributesThemeableView.swift
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
  Rocket.Chat/Views/Cells/LoaderTableViewCell.xib
  Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerView.xib
  Rocket.Chat/Views/Chat/ChatTitleView.xib
  Rocket.Chat/Views/Sections/SubscriptionSectionView.xib
  Rocket.Chat/Views/Subscriptions/ServersListView.xib
  Rocket.ChatTests/API/Clients/SpotlightClientSpec.swift
  Rocket.ChatTests/Models/Auth/AuthSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: ♻️ refactor, ⚠️ remove warnings, 🚚 chore

#2032 [ROUTINE] Set proper assets' scales for pdf images
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State black.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State dark.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State light.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/AttachFiles.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/ChooseFromLibrary.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/DrawSomething.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/RecordVideo.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/TakeAPhoto.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Cancel.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Error.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_File.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Image.imageset/Contents.json
Labels: 🚚 chore

#2033 [IMPROVEMENT] Fix theming for administration web view
  Rocket.Chat/Controllers/WebViewEmbedded/WebViewControllerEmbedded.xib
Labels: 👍 improvement, 🖼 layout

#2042 [BUG] Highlighting does not stop when more than one person is tagged
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Extensions/NSRangeExtensions.swift
Labels: 🐛 bug

#2034 [FIX] Subscriptions should not repeat when they are grouped by type
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
Labels: 🐛 bug

#2044 [RELEASE] Merge DEVELOP into BETA
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Clients/SpotlightClient.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/RegisterUsernameTableViewController.swift
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Notification/NotificationViewController.xib
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewModel.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetail.storyboard
  Rocket.Chat/Controllers/User/UserDetail/UserDetailTableView.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
  Rocket.Chat/Controllers/WebViewEmbedded/WebViewControllerEmbedded.xib
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Extensions/NSRangeExtensions.swift
  Rocket.Chat/Extensions/UIButton/UIButtonCenterImage.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State black.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State dark.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Chat/Empty State light.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/AttachFiles.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/ChooseFromLibrary.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/DrawSomething.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/RecordVideo.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Composer/Attach/TakeAPhoto.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Cancel.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Error.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_File.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Message/Upload/Message_Upload_Image.imageset/Contents.json
  Rocket.Chat/Storyboards/Auth.storyboard
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Theme/RuntimeAttributesThemeableView.swift
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
  Rocket.Chat/Views/Cells/LoaderTableViewCell.xib
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCellCondensed.swift
  Rocket.Chat/Views/Chat/ChatBannerView/ChatBannerView.xib
  Rocket.Chat/Views/Chat/ChatTitleView.xib
  Rocket.Chat/Views/Chat/RCTextView.swift
  Rocket.Chat/Views/Sections/SubscriptionSectionView.xib
  Rocket.Chat/Views/Subscriptions/ServersListView.xib
  Rocket.ChatTests/API/Clients/SpotlightClientSpec.swift
  Rocket.ChatTests/Models/Auth/AuthSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: 💎 release: beta

#2047 [CRASH] Realm operating on the wrong thread on fallbacks for sendMessage & react
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
Labels: 💥 crash

#2049 [BUG] Hide login button when setting is disabled
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Storyboards/Chat.storyboard
Labels: 🐛 bug

#2051 [CHORE] Bouncing reactors & badge all the time for unreads
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.xib
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Labels: 👍 improvement, 🚚 chore

#2048 [BUG] Search needs to take in consideration user's full name & room's fname property
  Rocket.Chat/API/Requests/General/SpotlightRequest.swift
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
Labels: 🐛 bug

#2043 [FIX] Support on-premises WordPress OAuth
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/LoginService.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
Labels: 🐛 bug, 🔒 authentication

#2052 [IMPROVEMENT] Improve theming popovers
  Rocket.Chat/Controllers/Base/BaseViewController.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
Labels: 🌈 theme, 🚸 ux

#2053 [IMPROVEMENT] Use opaque cells for subscriptions table view
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Labels: 🐛 bug, 💥 crash

#2055 [BUG] Sometimes the user keeps looping to connect into the server (Realm becomes inconsistent
  Rocket.Chat/Managers/DatabaseManager.swift
Labels: 🐛 bug

#2061 [RELEASE] Merge DEVELOP into BETA
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/API/Requests/General/SpotlightRequest.swift
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Controllers/Base/BaseViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Controllers/User/UserDetail/UserDetailViewController.swift
  Rocket.Chat/Extensions/Models/SubscriptionExtensions.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.xib
  Rocket.Chat/Managers/DatabaseManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/LoginService.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Storyboards/Subscriptions.storyboard
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Subscriptions/ServersListView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingHeaderView.swift
  Rocket.Chat/Views/Subscriptions/SubscriptionsSortingView.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
Labels: 💎 release: beta

#2059 [i18n] Improvements in Russian translation
  Rocket.Chat/Resources/ru.lproj/InfoPlist.strings
Labels: 🌎 i18n

#2058 [i18n] Improvements in Russian translation
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🌎 i18n

#2063 [FIX] Owner user is not able to send message on a public readonly channel (issue #2003)
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
Labels: 🐛 bug

#2067 [CHORE] Update images to the new layout
  README.md
Labels: 📝 docs, 🚚 chore

#2070 Update images to the ones from App Store
  README.md
Labels: 📝 docs

#2065 [DOCS] Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: 📝 docs

#2064 [CRASH] RLMObject_Private.hpp line 45 ___ZN12_GLOBAL__N_115makeBoxedGetterIN5realm10
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/Base/BaseModel.swift
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Chat/ChatTitleView.swift
  Rocket.Chat/Views/Chat/ChatTitleViewModel.swift
Labels: 💥 crash

#2068 [IMPROVEMENT] Prevent fullscreen white image from obscuring close button & fix iPhone X layout
  Podfile.lock
Labels: 👍 improvement, 🚸 ux

#2071 [FIX] Notification reply not working when app is open and in other server
  Rocket.Chat/Managers/PushManager.swift
Labels: 🐛 bug

#2073 [IMPROVEMENT] Support https://go.rocket.chat/ deeplinks
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Helpers/DeepLink.swift
  Rocket.ChatTests/Helpers/DeepLinkSpec.swift
Labels: 👍 improvement

#2078 [DOCS] Update screenshots
  README.md
Labels: 📝 docs

#2079 [FIX] iPad losing right-side controller after becoming fullscreen on multitasking
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🐛 bug, 👀 needs review

#2080 [IMPROVEMENT] Don't hide Navigation Bar on Searching Rooms on iPad
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 👀 needs review, 👍 improvement, 🚸 ux

#2081 [FIX] Not being able to close reactor list in iPad compact mode
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
Labels: 🐛 bug, 👀 needs review, 🚸 ux

#2056 [IMPROVEMENT] Improve Share Extension experience
  Rocket.Chat.ShareExtension/Base/SENavigationController.swift
  Rocket.Chat.ShareExtension/Extensions/SEStateAPI.swift
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.ShareExtension/Rooms/SERoomsViewController.swift
  Rocket.Chat.ShareExtension/Rooms/SERoomsViewModel.swift
  Rocket.Chat.ShareExtension/State/ActionCreators/SelectServer.swift
  Rocket.Chat.ShareExtension/State/ActionCreators/SubmitContent.swift
  Rocket.Chat.ShareExtension/State/SESearchState.swift
  Rocket.Chat.ShareExtension/State/SEState.swift
  Rocket.Chat.ShareExtension/State/SEStore.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Models/Mapping/SESubscriptionModelMapping.swift
Labels: 👀 needs review, 👍 improvement, 🥃 share extension

#2088 [IMPROVEMENT] Improve Share Extension usability
  Rocket.Chat.ShareExtension/Base/SENavigationController.swift
  Rocket.Chat.ShareExtension/Rooms/SERoomsViewController.swift
  Rocket.Chat.ShareExtension/State/SEStore.swift
  Rocket.Chat/Models/Mapping/SESubscriptionModelMapping.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
Labels: 👍 improvement, 🚸 ux, 🥃 share extension

#2087 [FIX] iPhone plus navigation weird on landscape
  Rocket.Chat/Controllers/Base/MainSplitViewController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🐛 bug, 🚸 ux

#2089 [CHORE] Prepare app to release 3.0.3
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
Labels: 💎 release: beta

#2090 [RELEASE] Merge DEVELOP into BETA
  CONTRIBUTING.md
  Podfile.lock
  README.md
  Rocket.Chat.ShareExtension/Base/SENavigationController.swift
  Rocket.Chat.ShareExtension/Extensions/SEStateAPI.swift
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.ShareExtension/Rooms/SERoomsViewController.swift
  Rocket.Chat.ShareExtension/Rooms/SERoomsViewModel.swift
  Rocket.Chat.ShareExtension/State/ActionCreators/SelectServer.swift
  Rocket.Chat.ShareExtension/State/ActionCreators/SubmitContent.swift
  Rocket.Chat.ShareExtension/State/SESearchState.swift
  Rocket.Chat.ShareExtension/State/SEState.swift
  Rocket.Chat.ShareExtension/State/SEStore.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Controllers/Base/MainSplitViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Helpers/DeepLink.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/PushManager.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/Base/BaseModel.swift
  Rocket.Chat/Models/Mapping/SESubscriptionModelMapping.swift
  Rocket.Chat/Resources/ru.lproj/InfoPlist.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageAttachmentView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageAudioView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.xib
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Chat/ChatTitleView.swift
  Rocket.Chat/Views/Chat/ChatTitleViewModel.swift
  Rocket.ChatTests/Helpers/DeepLinkSpec.swift
Labels: 💎 release: beta

#2094 [RELEASE] Merge BETA into MASTER
  CONTRIBUTING.md
  Podfile.lock
  README.md
  Rocket.Chat.ShareExtension/Base/SENavigationController.swift
  Rocket.Chat.ShareExtension/Extensions/SEStateAPI.swift
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.ShareExtension/Rooms/SERoomsViewController.swift
  Rocket.Chat.ShareExtension/Rooms/SERoomsViewModel.swift
  Rocket.Chat.ShareExtension/State/ActionCreators/SelectServer.swift
  Rocket.Chat.ShareExtension/State/ActionCreators/SubmitContent.swift
  Rocket.Chat.ShareExtension/State/SESearchState.swift
  Rocket.Chat.ShareExtension/State/SEState.swift
  Rocket.Chat.ShareExtension/State/SEStore.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionsRequest.swift
  Rocket.Chat/Controllers/Base/MainSplitViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Helpers/DeepLink.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/PushManager.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/Base/BaseModel.swift
  Rocket.Chat/Models/Mapping/SESubscriptionModelMapping.swift
  Rocket.Chat/Resources/ru.lproj/InfoPlist.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageAttachmentView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageAudioView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.xib
  Rocket.Chat/Views/Cells/Chat/ChatMessageTextView.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageVideoView.swift
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Chat/ChatTitleView.swift
  Rocket.Chat/Views/Chat/ChatTitleViewModel.swift
  Rocket.ChatTests/Helpers/DeepLinkSpec.swift
Labels: 💎 release: master

#2092 [FIX] Filter hidden rooms from share extension
  Rocket.Chat.ShareExtension/State/SEState.swift
Labels: 🐛 bug, 🥃 share extension

#1396 [NEW] Menu for changing push notification settings
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Notifications/SaveNotificationRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionGetOneRequest.swift
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Preferences/Notifications/NotificationsCellProtocol.swift
  Rocket.Chat/Controllers/Preferences/Notifications/NotificationsChooseCell.swift
  Rocket.Chat/Controllers/Preferences/Notifications/NotificationsPreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/Notifications/NotificationsPreferencesViewModel.swift
  Rocket.Chat/Controllers/Preferences/Notifications/NotificationsSwitchCell.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Settings/PreferencesViewController.swift
  Rocket.Chat/Controllers/Settings/PreferencesViewModel.swift
  Rocket.Chat/Extensions/EnumExtensions.swift
  Rocket.Chat/Extensions/StringExtensions.swift
  Rocket.Chat/Helpers/Dynamic.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Notifications/NotificationPreferences.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Notifications.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Notifications.imageset/notification_icon.pdf
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.Chat/Storyboards/NotificationsSettings.storyboard
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/PickerView/RCPickerView.swift
  Rocket.ChatTests/API/Requests/Notifications/SaveNotificationRequestSpec.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionGetOneRequestSpec.swift
  Rocket.ChatTests/Controllers/NotificationsPreferences/NotificationsPreferencesEnumsSpec.swift
  Rocket.ChatTests/Controllers/NotificationsPreferences/NotificationsPreferencesViewModelSpec.swift
  Rocket.ChatTests/Models/SubscriptionNotificationssSpec.swift
Labels: 🎉 feature, 👀 needs review

#2095 [UPDATE] Update Realm, Nuke & Firebase from CocoaPods
  Podfile.lock
Labels: ⬆️ update dependencies
