Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-12, with the labels that each got.

#2394 [CRASH] AuthTableViewController.swift line 128 AuthTableViewController.viewDidLoad()
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
  Rocket.Chat/Controllers/Auth/AuthTableViewControllerLoginServices.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Labels: 💥 crash

#2397 [BUG] Color not being applied to text attachments
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseTextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
Labels: 🐛 bug

#2399 [BUG] Fixed problem with unread marker wrongly positioned
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
Labels: 🐛 bug

#2367 [IMPROVEMENT][RCVC] HintsView layout adjustments & user priority
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessagesComposerViewModel.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Extensions/Models/UserExtensions.swift
  Rocket.Chat/Extensions/UIViewController/UIViewControllerDimming.swift
Labels: 👍 improvement

#2401 [CHORE] Update SDK to fix the app build
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Labels: ⬆️ update dependencies

#2402 [CHORE] Full Dynamic Type support for messages & UI adjustments
  Rocket.Chat/Controllers/Chat/MessagesViewControllerSearching.swift
  Rocket.Chat/Helpers/MessageTextFontAttributes.swift
  Rocket.Chat/Managers/MarkdownManager.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Search.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Search.imageset/Search.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Search.imageset/Search@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Search.imageset/Search@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Search.imageset/magnifier.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Search.imageset/magnifier@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Search.imageset/magnifier@3x.png
  Rocket.Chat/Views/Chat/New Chat/Cells/DateSeparatorCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageURLCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/TextAttachmentMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/UnreadMarkerCell.swift
Labels: 👍 improvement, 🚚 chore

#2405 [FIX] Pushing multiple chat controllers on navigation stack when lagging
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🐛 bug

#2406 [FIX][RCVC] Autocompletion dimming chat without hints
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
Labels: 🐛 bug

#2357 [NEW] Header of conversations
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Add Button.imageset/plus.pdf
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChatSections/HeaderSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Models/ChatModels/MessageSectionModel.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/HeaderCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/HeaderCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/HeaderChatItem.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
Labels: 🎉 feature

#2409 [BUG] MessagesViewController keep in memory after closing chat rooms
  Podfile.lock
  Pods/Manifest.lock
  Pods/RocketChatViewController/Composer/Classes/Addons/Hints/HintsView.swift
  Pods/RocketChatViewController/Composer/Classes/Addons/Reply/ReplyView.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 👍 improvement

#2410 [BUG] Code adjustments, message update properties & user full name on the message
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
Labels: 🐛 bug, 🚚 chore

#2413 [DOCS] Add a "Reviewed by Hound" badge
  README.md
Labels: 📝 docs

#2414 [CRASH] Fixed a crash with invalid Realm thread
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 💥 crash

#2421 [CHORE] Make image and video components size be based on screen's proportion
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseVideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/ImageMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/VideoMessageCell.xib
Labels: 🚚 chore

#2422 [FIX] Attachment sorting
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
Labels: 🐛 bug

#2424 [CHORE] Update app version to 3.2 (222)
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
Labels: 🚚 chore

#2426 [FIX] Permissions API changed format on new endpoint
  Rocket.Chat/API/Requests/General/PermissionsRequest.swift
  Rocket.ChatTests/API/Clients/InfoClientSpec.swift
  Rocket.ChatTests/API/Requests/General/PermissionsRequestSpec.swift
Labels: 🐛 bug

#2427 [CHORE] Adjust spacing from basic message to other messages
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
Labels: 🖼 layout

#2428 [BUG][RCVC] Deleted messages are not removed from the list
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Requests/Message/DeleteMessageRequest.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 🐛 bug

#2429 [CHORE] Update RocketChatViewController with bug fixes
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Labels: 🚚 chore

#2416 [FIX][RCVC] Reintroduce "loading messages" indication
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Views/Chat/ChatTitleView.swift
Labels: 🐛 bug

#2433 [I18N] Update Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
Labels: 🌎 i18n

#2435 [IMPROVEMENT] Show emojis and markdown in reply/quote popup
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerReplying.swift
Labels: 👍 improvement

#2436 [IMPROVEMENT] Remove @ and add left & right spacing to mentions
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.ChatTests/Extensions/NSAttributedStringExtensionsSpec.swift
Labels: 👍 improvement

#2441 [NEW] Copy message permalink
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
  Rocket.Chat/Extensions/Models/SubscriptionPermalink.swift
  Rocket.Chat/Models/Message/MessageReply.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.ChatTests/Extensions/Models/SubscriptionPermalinkSpec.swift
  Rocket.ChatTests/Models/MessageSpec.swift
Labels: 🎉 feature

#2448 [CHORE] Remove code and support for servers below 0.62.0
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Clients/PushClient.swift
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/Model/CustomEmojiManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
Labels: 🐛 bug

#2449 [FIX][REGRESSION] Slash commands not working
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 🐛 bug

#2443 [I18N] Add new translations for italian strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
Labels: 🌎 i18n

#2446 [HOTFIX] Only show loading messages in initial request
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.ChatTests/Controllers/MessagesViewModelSpec.swift
Labels: 🔥 hotfix

#2452 [BUG] Mishandling message websocket updates
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
Labels: 🐛 bug

#2442 [FIX][REGRESSION] Not sending typing event
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MessagesSubscriptionViewModel.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerTyping.swift
  Rocket.Chat/Helpers/Throttle.swift
Labels: 🐛 bug

#2458 [I18N] Update Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
Labels: 🌎 i18n

#2461 [CHORE] Update RocketChatViewController
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/RocketChatViewController/Classes/RocketChatViewController.swift
Labels: 🚚 chore
