Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2018-04, with the labels that each got.

#1469 [RELEASE] Merge develop into beta
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/CommandsClient.swift
  Rocket.Chat/API/Clients/InfoClient.swift
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Extensions/Models/UserExtensions.swift
  Rocket.Chat/Extensions/RealmExtension.swift
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/Emojione.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Managers/Model/AuthManager.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Model/CustomEmojiManager.swift
  Rocket.Chat/Managers/Model/LoginServiceManager.swift
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.Chat/Managers/Model/PermissionManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager.swift
  Rocket.Chat/Models/Auth.swift
  Rocket.Chat/Models/Base/BaseModel.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.Chat/Models/Email.swift
  Rocket.Chat/Models/Mapping/UserModelMapping.swift
  Rocket.Chat/Models/Subscription.swift
  Rocket.Chat/Models/User.swift
  Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.swift
  Rocket.ChatTests/External/RCEmojiKit/EmojioneSpec.swift
  Rocket.ChatTests/Models/BaseModelSpec.swift
Labels: 💎 release: beta

#1471 [RELEASE] Merge beta into master
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/CommandsClient.swift
  Rocket.Chat/API/Clients/InfoClient.swift
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Extensions/Models/UserExtensions.swift
  Rocket.Chat/Extensions/RealmExtension.swift
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/Emojione.swift
  Rocket.Chat/External/RCEmojiKit/NSAttributedString+CustomEmojis.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Managers/Model/AuthManager.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Model/CustomEmojiManager.swift
  Rocket.Chat/Managers/Model/LoginServiceManager.swift
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.Chat/Managers/Model/PermissionManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager.swift
  Rocket.Chat/Models/Auth.swift
  Rocket.Chat/Models/Base/BaseModel.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.Chat/Models/Email.swift
  Rocket.Chat/Models/Mapping/UserModelMapping.swift
  Rocket.Chat/Models/Subscription.swift
  Rocket.Chat/Models/User.swift
  Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.swift
  Rocket.ChatTests/External/RCEmojiKit/EmojioneSpec.swift
  Rocket.ChatTests/Models/BaseModelSpec.swift
Labels: 💎 release: master

#1438 [CHORE] Reduce warnings
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Clients/UploadClient.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerConnectionHandler.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerLoginServices.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Controllers/Auth/SignupViewControllerCustomFields.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Controllers/Subscriptions/NewRoomViewController.swift
  Rocket.Chat/Drawing.storyboard
  Rocket.Chat/Helpers/DeepLink.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManager.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.Chat/Managers/PushManager.swift
  Rocket.Chat/Managers/Uploader/UploadManager.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCellAccessibility.swift
Labels: ⚠️ remove warnings, 👀 needs review

#1460 [NEW] Support pinning permissions & settings
  .gitignore
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Extensions/StringExtensions.swift
  Rocket.Chat/Extensions/URLExtension.swift
  Rocket.Chat/External/RCEmojiKit/Emojione+Transform.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/Helpers/Ask.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.Chat/Models/Auth.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Permission.swift
  Rocket.Chat/Models/Subscription.swift
  Rocket.Chat/Views/ColorPicker/ColorPickerView.swift
  Rocket.Chat/Views/Loader/LoaderView.swift
  Rocket.ChatTests/API/Middlewares/VersionMiddlewareSpec.swift
  Rocket.ChatTests/API/Requests/Authentication/LoginRequestSpec.swift
  Rocket.ChatTests/API/Requests/Authentication/MeRequestSpec.swift
  Rocket.ChatTests/API/Requests/Command/RunCommandRequestSpec.swift
  Rocket.ChatTests/API/Requests/InfoRequestSpec.swift
  Rocket.ChatTests/API/Requests/Message/DeleteMessageRequestSpec.swift
  Rocket.ChatTests/API/Requests/Message/PostMessageRequestSpec.swift
  Rocket.ChatTests/API/Requests/Message/UploadMessageRequestSpec.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionCreateRequestSpec.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionInfoRequestSpec.swift
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionMembersRequestSpec.swift
  Rocket.ChatTests/API/Requests/User/UpdateUserRequestSpec.swift
  Rocket.ChatTests/API/Requests/User/UploadAvatarRequestSpec.swift
  Rocket.ChatTests/API/Requests/User/UserInfoRequestSpec.swift
  Rocket.ChatTests/Controllers/NewRoomViewControllerSpec.swift
  Rocket.ChatTests/Extensions/NSAttributedStringExtensionsSpec.swift
  Rocket.ChatTests/Models/AuthSpec.swift
  Rocket.ChatTests/Models/PermissionSpec.swift
Labels: 🎉 feature, 👍 improvement

#1467 [CHORE] Project migrated to Swift 4.1
  .swiftlint.yml
  Rocket.Chat/API/Requests/Command/CommandsRequest.swift
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/External/RCEmojiKit/EmojiSearcher.swift
  Rocket.Chat/Managers/MessageTextCacheManager.swift
  Rocket.Chat/Models/CustomEmoji.swift
  Rocket.Chat/Models/Mapping/MessageModelMapping.swift
  Rocket.Chat/Models/Mapping/PermissionModelMapping.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Mapping/UserModelMapping.swift
  Rocket.Chat/Models/MessageReaction.swift
  Rocket.Chat/Views/Form/Cells/MentionsTextFieldTableViewCell.swift
  Rocket.ChatTests/Extensions/DateExtensionsSpec.swift
  circle.yml
Labels: 🛠 project

#1470 [FIX] Build URL that may use subdirectory
  Rocket.Chat/API/APIRequest.swift
  Rocket.Chat/Extensions/URLExtension.swift
  Rocket.ChatTests/Models/AuthSpec.swift
Labels: 🔥 hotfix

#1472 [IMPROVEMENT] Migrate "Emojis" RealTime request to REST
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Emoji/CustomEmojiRequest.swift
  Rocket.Chat/Managers/Model/CustomEmojiManager.swift
  Rocket.ChatTests/API/Requests/Emoji/CustomEmojiRequestSpec.swift
Labels: 👍 improvement

#1447 [IMPROVEMENT] Migrate reaction request to REST API
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Requests/Message/ReactMessageRequest.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageActions.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
  Rocket.ChatTests/API/Requests/Message/ReactMessageRequestSpec.swift
Labels: 👍 improvement, 📡 networking

#1480 [NEW] Allow user to see just the mentions of some channel
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Subscription/SubscriptionMentionsRequest.swift
  Rocket.Chat/API/Requests/Subscription/SubscriptionMessagesRequest.swift
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.ChatTests/API/Requests/Subscription/SubscriptionMentionsRequestSpec.swift
Labels: 🎉 feature

#1452 [IMPROVEMENT] Migrate spotlight call to REST API
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/SpotlightClient.swift
  Rocket.Chat/API/Requests/General/SpotlightRequest.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.ChatTests/API/Clients/SpotlightClientSpec.swift
  Rocket.ChatTests/API/Requests/General/InfoRequestSpec.swift
  Rocket.ChatTests/API/Requests/General/SpotlightRequestSpec.swift
Labels: 👀 needs review, 👍 improvement, 📡 networking

#1491 [CHORE] Update CocoaPods to 1.5.0 & a few of the Pods
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.ChatTests/API/Clients/CommandsClientSpec.swift
  Rocket.ChatTests/API/Clients/InfoClientSpec.swift
  Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
  Rocket.ChatTests/API/Clients/SpotlightClientSpec.swift
Labels: ⬆️ update dependencies

#1475 [DOCS] Creates a initial version of our planning document
  PLANNING.md
Labels: 📝 docs

#1505 [DOCS] Fixed some works in our planning document
  PLANNING.md
Labels: 📝 docs

#1503 [BUG] Random Invalid Session after upgrading sometimes
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.ChatTests/API/Clients/MessagesClientSpec.swift
Labels: 🐛 bug

#1476 [IMPROVEMENT] Migrate "Public Settings" from RealTime to REST
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/API/Version.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/Requests/InfoRequestHandler.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
  Rocket.ChatTests/API/VersionSpec.swift
Labels: 👍 improvement

#1507 [CI] Added the previously removed iOS 10 devices for Circle CI
  circle.yml
Labels: 👷 ci

#1502 [HOTFIX] Crash when sharing large files with share extension
  Rocket.Chat.ShareExtension/State/ActionCreators/ParseItemProviders.swift
  Rocket.Chat/API/Requests/Message/UploadMessageRequest.swift
  Rocket.Chat/Controllers/Language/LanguageViewController.swift
  Rocket.Chat/Managers/WebBrowserManager.swift
  Rocket.ChatTests/Controllers/OAuthViewControllerSpec.swift
  Rocket.ChatTests/External/RCEmojiKit/EmojioneSpec.swift
  Rocket.ChatTests/Settings/PreferencesViewModelSpec.swift
Labels: 💥 crash, 🔥 hotfix, 🥃 share extension

#1508 [IMPROVEMENT] Remove Google SignIn SDK (use our OAuth implementation)
  Podfile
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerGoogleExtensions.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerLoginServices.swift
  Rocket.Chat/Controllers/Auth/OAuthViewController.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.Chat/Managers/OAuthManager.swift
  Rocket.Chat/Models/LoginService.swift
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/google.imageset/Auth-Google.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/google.imageset/Auth-Google@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/google.imageset/Auth-Google@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/google.imageset/Contents.json
  Rocket.Chat/Storyboards/Auth.storyboard
Labels: 👍 improvement

#1511 [NEW] Add support to "Message_MaxAllowedSize" setting
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Chat/ChatViewControllerTextViewDelegate.swift
  Rocket.Chat/Helpers/Validators/MessageTextValidator.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
  Rocket.ChatTests/Helpers/MessageTextValidatorSpec.swift
Labels: 🎉 feature

#1512 [IMPROVEMENT] Reduce number of calls on /typing
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
Labels: 👍 improvement

#1526 [FIX] Edit Profile stuck when saving without changes
  Rocket.Chat/Controllers/Settings/EditProfileTableViewController.swift
Labels: 🐛 bug

#1530 [FIX] Rare crash when parsing markdown links
  Podfile.lock
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Extensions/NSAttributedStringExtensions.swift
  Rocket.Chat/Managers/MarkdownManager.swift
  Rocket.ChatTests/MarkdownManagerSpec.swift
Labels: 💥 crash

#1528 [IMPROVEMENT] Share extension: support 2 attachment combos
  Rocket.Chat.ShareExtension/Info.plist
Labels: 👍 improvement, 🥃 share extension

#1531 [FIX] Not opening corresponding room after pressing notification
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/DatabaseManager.swift
  Rocket.Chat/Managers/PushManager.swift
  Rocket.ChatTests/Managers/AppManagerSpec.swift
  Rocket.ChatTests/Managers/DatabaseManagerSpec.swift
  Rocket.ChatTests/Managers/PushManagerSpec.swift
Labels: 🐛 bug

#1504 [NEW] In-app notifications
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Notification/NotificationViewController.swift
  Rocket.Chat/Controllers/Notification/NotificationViewController.xib
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerMessages.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerRooms.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerSearch.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerTyping.swift
  Rocket.Chat/Managers/NotificationManager.swift
  Rocket.Chat/Managers/PushManager.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/ChatNotification.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/User/UserUtils.swift
  Rocket.Chat/Resources/chime.mp3
  Rocket.Chat/Views/Avatar/AvatarView.swift
  Rocket.Chat/Views/Notification/NotificationView.swift
  Rocket.Chat/Views/Notification/TransparentToTouchesWindow.swift
  Rocket.ChatTests/External/RCEmojiKit/EmojioneSpec.swift
  Rocket.ChatTests/Models/ChatNotificationSpec.swift
  Rocket.ChatTests/NotificationManagerSpec.swift
  Rocket.ChatTests/NotificationViewControllerSpec.swift
Labels: 🎉 feature, 🚨 needs changes

#1532 [NEW] Add support to Universal Links (go.rocket.chat)
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Rocket.Chat.entitlements
Labels: 🎉 feature

#1534 [CHORE] Update version of the app to new Beta release
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Info.plist
Labels: 💎 release: beta

#1539 [FIX] False positives on invalid session
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MainChatViewController.swift
  Rocket.Chat/Managers/Socket/Response/SocketError.swift
Labels: 🐛 bug

#1541 [CHORE] Merge develop into beta
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/MainChatViewController.swift
  Rocket.Chat/Managers/Socket/Response/SocketError.swift
Labels: 💎 release: beta

#1540 [CHORE] Remove + from the name, increment version & fix Instabug for Release builds
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Labels: 💎 release: beta, 🚚 chore

#1545 [RELEASE] Merge develop into beta
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Labels: 💎 release: beta

#1542 [IMPROVEMENT] Improve type-checking time of some methods
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Drawing/DrawingBrushOpacityViewController.swift
  Rocket.Chat/Extensions/String+Random.swift
  Rocket.Chat/Extensions/UIColorCSSColorsExtension.swift
  Rocket.ChatTests/Extensions/UIColorExtensionSpec.swift
Labels: 🛠 project

#1548 [DOCS] Updated README.md to say Swift 4.1
  README.md
Labels: 📝 docs

#1550 [IMPROVEMENT] Remove retain cycles on core chat hierarchy
  Rocket.Chat/Controllers/Chat/ChatControllerReplyHandler.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Chat/MainChatViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsViewController.swift
  Rocket.Chat/Managers/AppManager.swift
Labels: 👍 improvement

#1551 [FIX] Some messages are missing when loading history
  Rocket.Chat/Managers/Model/MessageManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Labels: 🐛 bug

#1555 [IMPROVEMENT] Clear chat when logging out
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Controllers/Chat/MainChatViewController.swift
Labels: 👍 improvement

#1553 [IMPROVEMENT] Investigate and update models that unnecessarily inherit from BaseModel
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Models/Attachment.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Mapping/ChannelModelMapping.swift
  Rocket.Chat/Models/Mapping/MentionModelMapping.swift
  Rocket.Chat/Models/Mapping/MessageURLModelMapping.swift
  Rocket.Chat/Models/Message/Channel.swift
  Rocket.Chat/Models/Message/Mention.swift
  Rocket.Chat/Models/Message/MessageReaction.swift
  Rocket.Chat/Models/Message/MessageURL.swift
  Rocket.ChatTests/Managers/AuthSettingsManagerSpec.swift
  Rocket.ChatTests/Models/ChannelSpec.swift
  Rocket.ChatTests/Models/MentionSpec.swift
  Rocket.ChatTests/Models/MessageReactionSpec.swift
  Rocket.ChatTests/Models/MessageURLSpec.swift
Labels: 👍 improvement

#1564 [IMPROVEMENT] Missing translation/Updated german
  Rocket.Chat.ShareExtension/Resources/cs.lproj/Localizable.strings
  Rocket.Chat.ShareExtension/Resources/de.lproj/Localizable.strings
  Rocket.Chat.ShareExtension/Resources/el.lproj/Localizable.strings
  Rocket.Chat.ShareExtension/Resources/fr.lproj/Localizable.strings
  Rocket.Chat.ShareExtension/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/External/RCEmojiKit/de.lproj/RCEmojiKit.strings
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
Labels: 🌎 i18n

#1560 [IMPROVEMENT] Improve the message of SSL invalid when connecting to the server
  Rocket.Chat/API/API.swift
  Rocket.Chat/API/APIError.swift
  Rocket.Chat/Managers/Requests/InfoRequestHandler.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Labels: 👍 improvement

#1490 [IMPROVEMENT] Migrate login services fetching to REST API
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/InfoClient.swift
  Rocket.Chat/API/Requests/General/LoginServicesRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerLoginServices.swift
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
  Rocket.ChatTests/API/Clients/InfoClientSpec.swift
Labels: 👍 improvement, 📡 networking

#1565 [I18N] Remove the "Message" string from actions
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
Labels: 🌎 i18n

#1572 [CHORE] Organize Xcode project files
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Drawing/Color Picker/ColorPickerView.swift
  Rocket.Chat/Controllers/Drawing/DrawingBrushColorViewModel.swift
  Rocket.Chat/Controllers/Drawing/DrawingViewController.swift
  Rocket.Chat/Controllers/Drawing/DrawingViewModel.swift
  Rocket.Chat/Controllers/Preferences/ChangeAppIcon/ChangeAppIconCell.swift
  Rocket.Chat/Controllers/Preferences/ChangeAppIcon/ChangeAppIconViewController.swift
  Rocket.Chat/Controllers/Preferences/ChangeAppIcon/ChangeAppIconViewModel.swift
  Rocket.Chat/Controllers/Preferences/Language/ChangeLanguageCell.swift
  Rocket.Chat/Controllers/Preferences/Language/ChangeLanguageResetCell.swift
  Rocket.Chat/Controllers/Preferences/Language/LanguageViewController.swift
  Rocket.Chat/Controllers/Preferences/Language/LanguageViewModel.swift
  Rocket.Chat/Controllers/Preferences/PreferencesNavigationController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewModel.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileViewModel.swift
  Rocket.Chat/Controllers/Preferences/Profile/NewPasswordTableViewController.swift
  Rocket.Chat/Controllers/Preferences/Profile/NewPasswordViewModel.swift
  Rocket.Chat/Controllers/Preferences/Web Browser/WebBrowserTableViewController.swift
  Rocket.Chat/Controllers/Preferences/Web Browser/WebBrowserViewModel.swift
  Rocket.Chat/Managers/Uploader/UploadVideoCompression.swift
  Rocket.Chat/Storyboards/Base.lproj/LaunchScreen.storyboard
  Rocket.Chat/Storyboards/Drawing.storyboard
  Rocket.Chat/Views/UIPickerView/CompoundPickerViewDelegate.swift
  Rocket.Chat/Views/UIPickerView/PickerViewDelegate.swift
  Rocket.ChatTests/Controllers/NotificationViewControllerSpec.swift
  Rocket.ChatTests/Managers/MarkdownManagerSpec.swift
  Rocket.ChatTests/Managers/NotificationManagerSpec.swift
  Rocket.ChatTests/Managers/Requests/InfoRequestHandlerSpec.swift
  Rocket.ChatTests/Managers/Socket/SocketManagerSpec.swift
  Rocket.ChatTests/Preferences/AppIcon/ChangeAppIconViewModelSpec.swift
  Rocket.ChatTests/Preferences/Language/LanguageViewModelSpec.swift
  Rocket.ChatTests/Preferences/PreferencesViewModelSpec.swift
  Rocket.ChatTests/Preferences/Profile/EditProfileViewModelSpec.swift
  Rocket.ChatTests/Preferences/Profile/NewPasswordViewModelSpec.swift
  Rocket.ChatTests/Preferences/Web Browser/WebBrowserViewModelSpec.swift
  Rocket.ChatTests/Views/CreateChannel/MentionsTextFieldTableViewCellSpec.swift
Labels: 🚚 chore

#1580 [CHORE] Update RCMarkdownParser (fix alt link parsing)
  Podfile.lock
Labels: 🐛 bug

#1579 [HOTFIX] Login services not mapping correctly
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
Labels: 🔥 hotfix

#1581 [NEW] Indicate own username
  Rocket.Chat/Controllers/Chat/ChatControllerAutocomplete.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Labels: 🎉 feature

#1582 [FIX] Share extension not working with Notes and App Store
  Rocket.Chat.ShareExtension/Base/SENavigationController.swift
  Rocket.Chat.ShareExtension/Info.plist
Labels: 🐛 bug, 🥃 share extension

#1584 [NEW] Fabric tracking as an option
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/API.swift
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewModel.swift
  Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.ChatTests/Managers/Launcher/BugTrackingCoordinatorSpec.swift
  Rocket.ChatTests/Preferences/PreferencesViewModelSpec.swift
  Rocket.ChatTests/Views/Chat/ChatMessageTextViewModelSpec.swift
Labels: 🎉 feature

#1588 [NEW] Add support to "First_Channel_After_Login" setting
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/AppDelegate.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerAuthenticationHandler.swift
  Rocket.Chat/Extensions/Models/AuthInternalExtensions.swift
  Rocket.Chat/Extensions/Models/AuthSettingsHiddenTypes.swift
  Rocket.Chat/Extensions/RealmExecute.swift
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Managers/Model/AuthManager/AuthManagerSocket.swift
  Rocket.Chat/Managers/Model/AuthSettingsManager.swift
  Rocket.Chat/Managers/PushManager.swift
  Rocket.Chat/Managers/Socket/SocketManager.swift
  Rocket.Chat/Models/Auth/Auth.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Subscription/SubscriptionQueries.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
  Rocket.ChatTests/Models/AuthSpec.swift
  Rocket.ChatTests/Models/SubscriptionQueriesSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: 🎉 feature, 👀 needs review

#1594 [NEW] Support API_Gitlab_URL setting
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerLoginServices.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/LoginService.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
Labels: 🎉 feature, 👀 needs review, 🔒 authentication

#1597 [FIX] Fixed notification not being parsed when the user's name is not present
  Rocket.Chat/Models/ChatNotification.swift
Labels: 🐛 bug

#1599 [IMPROVEMENT] Improve message rendering, updates and equal checks
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Clock.imageset/Clock.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Clock.imageset/Clock@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Clock.imageset/Clock@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Clock.imageset/Contents.json
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.xib
  Rocket.ChatTests/Models/MessageSpec.swift
Labels: 👍 improvement

#1589 [NEW] Add server version to preferences & Fabric reports
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewModel.swift
  Rocket.Chat/Managers/Launcher/BugTrackingCoordinator.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Preferences.storyboard
  Rocket.ChatTests/API/Clients/InfoClientSpec.swift
  Rocket.ChatTests/Preferences/PreferencesViewModelSpec.swift
Labels: 🎉 feature, 👀 needs review

#1596 [NEW] Search by messages in a channel/group/DM
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Requests/Message/SearchMessagesRequest.swift
  Rocket.Chat/Controllers/Chat/ChatViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesListControllerSearch.swift
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Storyboards/Chat.storyboard
  Rocket.ChatTests/API/Requests/Message/SearchMessagesRequestSpec.swift
Labels: 🎉 feature

#1600 [CHORE] Update app & build version to 2.3.0
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Info.plist
Labels: 💎 release: beta

#1601 [IMPROVEMENT] Logic of signup button hiding & some code adjustments
  Rocket.Chat/Controllers/Auth/AuthViewController.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerLoginServices.swift
Labels: 👀 needs review, 👍 improvement

#1527 [NEW] Support WordPress authentication
  Rocket.Chat/API/Requests/General/PublicSettingsRequest.swift
  Rocket.Chat/Controllers/Auth/AuthViewControllerLoginServices.swift
  Rocket.Chat/Models/AuthSettings.swift
  Rocket.Chat/Models/LoginService.swift
  Rocket.Chat/Models/Mapping/AuthSettingsModelMapping.swift
  Rocket.Chat/Models/Mapping/LoginServiceModelMapping.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/wordpress.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/wordpress.imageset/wordpress@1x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/wordpress.imageset/wordpress@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Auth/wordpress.imageset/wordpress@3x.png
  Rocket.ChatTests/API/Requests/General/PublicSettingsRequestSpec.swift
Labels: 🎉 feature, 👀 needs review, 🔒 authentication

#1607 [FIX] Search messages bug on iPhone X
  Rocket.Chat/Storyboards/Chat.storyboard
Labels: 🐛 bug, 🖼 layout

#1605 [IMPROVEMENT] Show action sheet when tapping usernames, mentions, etc
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChannelInfoViewController.swift
  Rocket.Chat/Controllers/Chat/ChatControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/MembersListViewController.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Views/ActionSheets/UserActionSheetPresenter.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/MemberCell.swift
  Rocket.Chat/Views/Chat/RCTextView.swift
Labels: 👀 needs review, 👍 improvement, 🚸 ux

#1610 [FIX] Custom emojis not updating when changing servers
  Rocket.Chat/Managers/Model/CustomEmojiManager.swift
Labels: 🐛 bug

#1612 [FIX] Logic on sending sequencial messages when the screen appears
  Rocket.Chat/Controllers/Chat/ChatDataController.swift
  Rocket.Chat/Models/Message/MessageReply.swift
Labels: 🐛 bug

#1613 [CHORE] Increment version to release 2.3.0
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
Labels: 💎 release: master
