Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2019-01, with the labels that each got.

#2455 [IMPROVEMENT] Move message history loading to REST API
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/API/Requests/Room/RoomHistoryRequest.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Extensions/DateExtension.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
  Rocket.ChatTests/API/Clients/SubscriptionsClientSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomHistoryRequestSpec.swift
Labels: 👍 improvement, 📡 networking

#2467 [IMPROVEMENT] Optimize "mark as read" requests API
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
Labels: 👍 improvement

#2470 [FIX] Do not return NaN values or negative values from the sizing manager
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesSizingManager.swift
  Rocket.Chat/Views/Cells/Auth/AuthSeparatorTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/LoginServiceTableViewCell.swift
  Rocket.Chat/Views/Cells/Auth/ShowMoreSeparatorTableViewCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageDaySeparator.swift
  Rocket.ChatTests/Controllers/MessagesSizingViewModelSpec.swift
Labels: 🐛 bug, 💥 crash

#2478 [FIX] Issues with Dynamic Typing being different than expected
  Rocket.Chat/Helpers/MessageTextFontAttributes.swift
Labels: 🐛 bug

#2479 [FIX] Use Accelerate framework to resize UIImage in order to use much less memory for the share extension
  Rocket.Chat/Extensions/UIImageExtension.swift
Labels: 💥 crash

#2483 [I18N] Add Chinese Simplified language support to the app
  Rocket.Chat.ShareExtension/Resources/zh-Hans.lproj/Localizable.strings
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/zh-Hans.lproj/RCEmojiKit.strings
  Rocket.Chat/Resources/zh-Hans.lproj/InfoPlist.strings
  Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hans.lproj/VoiceOver.strings
Labels: 🌎 i18n

#2494 [IMPROVEMENT] Add editing changed handler to UITextField in connect screen
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
  Rocket.Chat/Storyboards/Auth.storyboard
Labels: 👍 improvement

#2493 [FIX] Fixed issues with duplicated subscription or missing on the list
  Rocket.Chat/API/Clients/MessagesClient.swift
  Rocket.Chat/API/Clients/SpotlightClient.swift
  Rocket.Chat/API/Clients/SubscriptionsClient.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerJoining.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManagerRooms.swift
  Rocket.Chat/Managers/Socket/Response/ResponseMessage.swift
  Rocket.Chat/Managers/Socket/Response/SocketHandlers.swift
  Rocket.Chat/Models/Base/ModelHandler.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.ChatTests/API/Clients/SubscriptionsClientSpec.swift
  Rocket.ChatTests/API/Requests/Room/RoomHistoryRequestSpec.swift
  Rocket.ChatTests/Extensions/NSAttributedStringExtensionsSpec.swift
Labels: 🐛 bug

#2500 [FIX] Crash on tapping Wordpress or sometimes other external services on Login screen
  Rocket.Chat/Controllers/Auth/AuthTableViewController.swift
Labels: 🐛 bug, 💥 crash

#2501 [I18N] Translate italian strings for video calls
  Rocket.Chat/Resources/it.lproj/Localizable.strings
Labels: 🌎 i18n

#2510 [CHORE] Remove the feature to block users locally from the app
  Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
  Rocket.Chat/Managers/Model/MessageManager/MessageManager.swift
  Rocket.Chat/Models/Mapping/MessageModelMapping.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Models/Subscription/SubscriptionUtils.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
Labels: 🚚 chore

#2511 [FIX] Read receipts missing on the list of messages
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BasicMessageCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/SequentialMessageCell.xib
Labels: 🐛 bug

#2516 [CHORE] Replace DM icon by bubble on titleView
  Rocket.Chat/Views/Chat/ChatTitleView.swift
  Rocket.Chat/Views/Chat/ChatTitleView.xib
Labels: 🖼 layout

#2514 [NEW] Support announcements
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/Subscription/UnmanagedSubscription.swift
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
  Rocket.Chat/Views/Chat/ChatAnnouncementView.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
Labels: 🎉 feature

#2517 [CHORE] Remove unused code, resolve some SwiftLint warnings & suppress couple.
  Pods/Pods.xcodeproj/project.pbxproj
  Rocket.Chat.xcodeproj/xcshareddata/xcschemes/Rocket.Chat.xcscheme
  Rocket.Chat/Controllers/Chat/MessagesListViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerUploading.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Controllers/Preferences/PreferencesViewController.swift
  Rocket.Chat/Managers/Uploader/UploadManager.swift
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageCell.swift
  Rocket.Chat/Views/Cells/Chat/ChatMessageImageView.swift
  Rocket.Chat/Views/Cells/Hints/TextHintEmojiViewCell.swift
  Rocket.Chat/Views/Cells/Hints/TextHintLabelCell.swift
  Rocket.Chat/Views/Cells/Hints/UserHintAvatarViewCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseImageMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/BaseQuoteMessageCell.swift
Labels: 🚚 chore

#2521 [CHORE] Remove @ from file attachments, autocomplete & quotes
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Models/Mapping/AttachmentModelMapping.swift
  Rocket.Chat/Views/Subscriptions/FileTableViewCell.swift
Labels: 🚚 chore

#2523 [FIX] View models deallocation & Subscription object mapping fixing on updates
  Rocket.Chat/Controllers/Chat/MessagesSubscriptionViewModel.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
  Rocket.Chat/Managers/Model/SubscriptionManager/SubscriptionManager.swift
Labels: 🐛 bug

#2524 [FIX] Fixed color into forgot password button
  Rocket.Chat/Controllers/Auth/LoginTableViewController.swift
Labels: 🌈 theme, 🐛 bug

#2525 [FIX] Fixed issue on connecting to a server & having an invalid server after all in some edge cases
  Rocket.Chat/Controllers/Auth/ConnectServerViewController.swift
Labels: 🐛 bug
