Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2019-03, with the labels that each got.

#2582 [FIX] Status not updated immediately after selecting
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
Labels: 🐛 bug

#2576 [I18N] Update Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
Labels: 🌎 i18n

#2587 [NEW] Add Traditional Chinese (zh-TW) translation file
  Rocket.Chat.ShareExtension/Resources/zh-Hant.lproj/Localizable.strings
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/External/RCEmojiKit/zh-Hant.lproj/RCEmojiKit.strings
  Rocket.Chat/Resources/zh-Hant.lproj/InfoPlist.strings
  Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hant.lproj/VoiceOver.strings
Labels: 🌎 i18n

#2485 [NEW] Record audio & send it
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Discard Button.imageset/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Discard Button.imageset/trash.pdf
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Pause Button.imageset/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Pause Button.imageset/pause.pdf
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Play Button.imageset/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Play Button.imageset/play.pdf
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Slider Thumb.imageset/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Slider Thumb.imageset/Player Progress Button.png
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Slider Thumb.imageset/Player Progress Button@2x.png
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Preview Audio View/Slider Thumb.imageset/Player Progress Button@3x.png
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Record Audio View/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Record Audio View/Gray Arrow Left.imageset/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Record Audio View/Gray Arrow Left.imageset/arrowBackGrey.pdf
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Record Audio View/Red Mic Button.imageset/Contents.json
  Pods/RocketChatViewController/Composer/Assets/Assets.xcassets/Overlays/Record Audio View/Red Mic Button.imageset/icRec.pdf
  Pods/RocketChatViewController/Composer/Assets/cs.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/de.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/el.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/en.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/es.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/fr.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/ja.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/pl.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/pt-BR.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/pt-PT.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Assets/ru.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Classes/Addons/Editing/EditingView.swift
  Pods/RocketChatViewController/Composer/Classes/Addons/Reply/ReplyView.swift
  Pods/RocketChatViewController/Composer/Classes/ComposerAssets.swift
  Pods/RocketChatViewController/Composer/Classes/Delegate/ComposerViewDelegate.swift
  Pods/RocketChatViewController/Composer/Classes/Delegate/ComposerViewExpandedDelegate.swift
  Pods/RocketChatViewController/Composer/Classes/Library/AudioRecorder.swift
  Pods/RocketChatViewController/Composer/Classes/Library/ComposerLocalizable.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/OverlayView.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/PreviewAudioView.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/RecordAudioView.swift
  Pods/RocketChatViewController/Composer/Classes/Views/ComposerView.swift
  Rocket.Chat/Controllers/Base/Main/MainSplitViewControllerShortcuts.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerSending.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerUploading.swift
  Rocket.Chat/Helpers/ShortcutHelpers.swift
  Rocket.Chat/Theme/ThemeableViews.swift
Labels: 🎉 feature

#2589 [CHORE] Update RocketChatViewController SDK to use haptic feedback & DifferenceKit to 1.0
  Podfile
  Podfile.lock
  Pods/DifferenceKit/README.md
  Pods/DifferenceKit/Sources/AnyDifferentiable.swift
  Pods/Local Podspecs/RocketChatViewController.podspec.json
  Pods/Manifest.lock
  Pods/RocketChatViewController/Composer/Classes/Overlays/RecordAudioView.swift
  Pods/Target Support Files/DifferenceKit-Core/Info.plist
  Pods/Target Support Files/DifferenceKit/Info.plist
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Info.plist
  Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings
Labels: ⬆️ update dependencies

#2590 [NEW] Try to open links as an universal URL instead of directly on the browser
  Rocket.Chat/Managers/WebBrowserManager.swift
Labels: 🎉 feature

#2591 [IMPROVEMENT] Support authentication parameters on avatars
  Rocket.Chat/Models/User/User.swift
Labels: 👍 improvement

#2592 [IMPROVEMENT] Better task management on Directory
  Rocket.Chat/Controllers/Directory/DirectoryViewController.swift
  Rocket.Chat/Controllers/Directory/DirectoryViewModel.swift
  Rocket.Chat/Views/Directory/DirectoryFiltersView.swift
Labels: 👍 improvement

#2593 [CHORE] Add events to Directory & Audio Messages
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Directory/DirectoryViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/AnalyticsManager.swift
  Rocket.ChatTests/Models/UserSpec.swift
Labels: 📊 analytics

#2599 [IMPROVEMENT] Auto suggesting slash commands even when not first character
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
Labels: 👍 improvement

#2602 [FIX] Clear listeners for dynamic value in notifications
  Rocket.Chat/Controllers/Preferences/Notifications/NotificationsChooseCell.swift
  Rocket.Chat/Helpers/Dynamic.swift
Labels: 🐛 bug

#2600 [IMPROVEMENT] Change theme for MBProgressHUD
  Rocket.Chat/Theme/ThemeableViews.swift
Labels: 🌈 theme, 👍 improvement

#2603 [IMPROVEMENT] Allow scrolling of chat title if it doesn’t fit
  Rocket.Chat/Views/Chat/ChatTitleView.swift
  Rocket.Chat/Views/Chat/ChatTitleView.xib
  Rocket.ChatTests/Views/Chat/ChatTitleViewSpec.swift
Labels: 👍 improvement

#2601 [i18n] Add missing polish translations
  Rocket.Chat.ShareExtension/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/External/RCEmojiKit/pl.lproj/RCEmojiKit.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
Labels: 🌎 i18n

#2604 [IMPROVEMENT] Adjust wording of Members in Directory
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings
Labels: 👍 improvement

#2609 [CHORE] Update RocketChatViewController with audio recorder feedback sounds
  Podfile.lock
  Pods/Local Podspecs/RocketChatViewController.podspec.json
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Assets/pl.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Classes/ComposerAssets.swift
  Pods/RocketChatViewController/Composer/Classes/Delegate/ComposerViewExpandedDelegate.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/RecordAudioView.swift
  Pods/RocketChatViewController/Composer/Sounds/cancel_audio_record.m4a
  Pods/RocketChatViewController/Composer/Sounds/start_audio_record.m4a
Labels: ⬆️ update dependencies, 👍 improvement

#2608 [FIX] Refactor EmojiPickerViewController and fix memory leak on iPhone
  Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPickerController.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListViewController.swift
  Rocket.Chat/External/RCEmojiKit/pl.lproj/RCEmojiKit.strings
Labels: 🐛 bug

#2610 [CHORE] Update SDK with haptic feedback working again
  Podfile.lock
  Pods/Manifest.lock
  Pods/RocketChatViewController/Composer/Classes/Overlays/RecordAudioView.swift
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
Labels: ⬆️ update dependencies

#2611 [CHORE] Merge DEVELOP into BETA
  Podfile.lock
  Pods/Local Podspecs/RocketChatViewController.podspec.json
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/RocketChatViewController/Composer/Assets/pl.lproj/Localizable.strings
  Pods/RocketChatViewController/Composer/Classes/ComposerAssets.swift
  Pods/RocketChatViewController/Composer/Classes/Delegate/ComposerViewExpandedDelegate.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/RecordAudioView.swift
  Pods/RocketChatViewController/Composer/Sounds/cancel_audio_record.m4a
  Pods/RocketChatViewController/Composer/Sounds/start_audio_record.m4a
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.ShareExtension/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Controllers/Chat/MessagesViewControllerComposerDelegate.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerMessageCellProtocol.swift
  Rocket.Chat/Controllers/Preferences/Notifications/NotificationsChooseCell.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPicker.swift
  Rocket.Chat/External/RCEmojiKit/Views/EmojiPicker/EmojiPickerController.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListView.swift
  Rocket.Chat/External/RCEmojiKit/Views/Reaction/ReactorListViewController.swift
  Rocket.Chat/External/RCEmojiKit/pl.lproj/RCEmojiKit.strings
  Rocket.Chat/Helpers/Dynamic.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings
  Rocket.Chat/Theme/ThemeableViews.swift
  Rocket.Chat/Views/Chat/ChatTitleView.swift
  Rocket.Chat/Views/Chat/ChatTitleView.xib
  Rocket.ChatTests/Views/Chat/ChatTitleViewSpec.swift
Labels: 💎 release: beta

#2618 [CHORE] UI adjustments on the list of chats
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
Labels: 🖼 layout

#2619 [CHORE] Update RocketChatViewController with better audio feedback, bug fixes and more
  Podfile.lock
  Pods/Manifest.lock
  Pods/RocketChatViewController/Composer/Classes/Library/AudioRecorder.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/PreviewAudioView.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/RecordAudioView.swift
Labels: ⬆️ update dependencies
