Repository RocketChat/Rocket.Chat.iOS, pull requests merged in 2019-04, with the labels that each got.

#2623 [I18N] Greek translation update 2019-03-30
  Rocket.Chat/Resources/el.lproj/Localizable.strings
Labels: 🌎 i18n

#2620 [FIX] Auth params into channel avatar URL
  Rocket.Chat/Models/Subscription/Subscription.swift
Labels: 🐛 bug

#2624 [FIX] User is loosing roles on mapping lastMessage
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
Labels: 🐛 bug

#2626 [CHORE] UI adjustments on quotes & replies
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
Labels: 🖼 layout

#2621 [CHORE] Merge DEVELOP into BETA
  Podfile.lock
  Pods/Manifest.lock
  Pods/RocketChatViewController/Composer/Classes/Library/AudioRecorder.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/PreviewAudioView.swift
  Pods/RocketChatViewController/Composer/Classes/Overlays/RecordAudioView.swift
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat/Info.plist
  Rocket.Chat/Models/Mapping/SubscriptionModelMapping.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/SubscriptionCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/QuoteMessageCell.xib
Labels: 💎 release: beta

#2629 [FIX] "Join Channel" button overlapping home bar on iPhone X/Xr/Xs/Max
  Rocket.Chat/Controllers/Chat/MessagesViewControllerJoining.swift
Labels: 🐛 bug

#2640 [FIX] Navigation bar disappears after subscription search
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 🐛 bug

#2641 [CHORE] Update MobilePlayer Pod for iPhone XR/XS Max support
  Podfile.lock
  Pods/Local Podspecs/MobilePlayer.podspec.json
  Pods/Manifest.lock
  Pods/MobilePlayer/MobilePlayer/Extensions/ClosureSupport.swift
  Pods/MobilePlayer/MobilePlayer/Extensions/UIColor+Hex.swift
  Pods/MobilePlayer/MobilePlayer/Helpers/StateHelper.swift
  Pods/MobilePlayer/MobilePlayer/MobilePlayerViewController.swift
  Pods/MobilePlayer/MobilePlayer/Parsers/YoutubeParser.swift
  Pods/MobilePlayer/MobilePlayer/Views/MobilePlayerControlsView.swift
  Pods/MobilePlayer/MobilePlayer/Views/Slider.swift
  Pods/MobilePlayer/README.md
  Pods/Pods.xcodeproj/project.pbxproj
  Pods/Target Support Files/MobilePlayer/Info.plist
  Pods/Target Support Files/MobilePlayer/MobilePlayer.xcconfig
  Pods/Target Support Files/MobilePlayer/ResourceBundle-MobilePlayer-Info.plist
Labels: ⬆️ update dependencies, 🐛 bug

#2646 [NEW] Initial support to Discussions
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Chat/MessagesViewControllerJoining.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Models/Mapping/MessageModelMapping.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/Subscription/UnmanagedSubscription.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Discussions.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Discussions.imageset/Discussions.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Discussions.imageset/Discussions@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Discussions.imageset/Discussions@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Cell Subscription Discussion.imageset/Cell Subscription Discussion.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Cell Subscription Discussion.imageset/Cell Subscription Discussion@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Cell Subscription Discussion.imageset/Cell Subscription Discussion@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Cell Subscription Discussion.imageset/Contents.json
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.xib
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.xib
  Rocket.Chat/Views/Chat/ChatTitleViewModel.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageDiscussionCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageDiscussionCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageVideoCallCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/MessageDiscussionChatItem.swift
  Rocket.ChatTests/Models/MessageSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
  Rocket.ChatTests/Models/UnmanagedMessageSpec.swift
Labels: 🎉 feature

#2647 [FIX] ShareExtension references to Discussion
  Rocket.Chat.ShareExtension/Compose/SEComposeHeaderViewModel.swift
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.ShareExtension/Rooms/SERoomCellModel.swift
  Rocket.Chat/Info.plist
Labels: 🐛 bug

#2651 [RELEASE] Merge DEVELOP into BETA
  Podfile
  Podfile.lock
  Pods/Manifest.lock
  Pods/Pods.xcodeproj/project.pbxproj
  Rocket.Chat.ShareExtension/Compose/SEComposeHeaderViewModel.swift
  Rocket.Chat.ShareExtension/Info.plist
  Rocket.Chat.ShareExtension/Rooms/SERoomCellModel.swift
  Rocket.Chat.xcodeproj/project.pbxproj
  Rocket.Chat/Controllers/Chat/ChannelActionsViewController.swift
  Rocket.Chat/Controllers/Chat/ChatSections/MessageSection.swift
  Rocket.Chat/Controllers/Chat/MessagesViewController.swift
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
  Rocket.Chat/Info.plist
  Rocket.Chat/Managers/AppManager.swift
  Rocket.Chat/Models/Mapping/MessageModelMapping.swift
  Rocket.Chat/Models/Message/Message.swift
  Rocket.Chat/Models/Message/UnmanagedMessage.swift
  Rocket.Chat/Models/Subscription/Subscription.swift
  Rocket.Chat/Models/Subscription/UnmanagedSubscription.swift
  Rocket.Chat/Resources/Assets.xcassets/Icons/Discussions.imageset/Contents.json
  Rocket.Chat/Resources/Assets.xcassets/Icons/Discussions.imageset/Discussions.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Discussions.imageset/Discussions@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Discussions.imageset/Discussions@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Cell Subscription Discussion.imageset/Cell Subscription Discussion.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Cell Subscription Discussion.imageset/Cell Subscription Discussion@2x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Cell Subscription Discussion.imageset/Cell Subscription Discussion@3x.png
  Rocket.Chat/Resources/Assets.xcassets/Icons/Subscriptions/Cell Subscription Discussion.imageset/Contents.json
  Rocket.Chat/Resources/cs.lproj/Localizable.strings
  Rocket.Chat/Resources/de.lproj/Localizable.strings
  Rocket.Chat/Resources/el.lproj/Localizable.strings
  Rocket.Chat/Resources/en.lproj/Localizable.strings
  Rocket.Chat/Resources/es.lproj/Localizable.strings
  Rocket.Chat/Resources/fr.lproj/Localizable.strings
  Rocket.Chat/Resources/it.lproj/Localizable.strings
  Rocket.Chat/Resources/ja.lproj/Localizable.strings
  Rocket.Chat/Resources/pl.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-BR.lproj/Localizable.strings
  Rocket.Chat/Resources/pt-PT.lproj/Localizable.strings
  Rocket.Chat/Resources/ru.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hans.lproj/Localizable.strings
  Rocket.Chat/Resources/zh-Hant.lproj/Localizable.strings
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.swift
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoBasicCell.xib
  Rocket.Chat/Views/Cells/Chat/Info/ChannelInfoDescriptionCell.xib
  Rocket.Chat/Views/Cells/Subscription/BaseSubscriptionCell.swift
  Rocket.Chat/Views/Cells/Subscription/ChatPreviewModeView.xib
  Rocket.Chat/Views/Chat/ChatTitleViewModel.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageDiscussionCell.swift
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageDiscussionCell.xib
  Rocket.Chat/Views/Chat/New Chat/Cells/MessageVideoCallCell.xib
  Rocket.Chat/Views/Chat/New Chat/ChatItems/MessageDiscussionChatItem.swift
  Rocket.ChatTests/Models/MessageSpec.swift
  Rocket.ChatTests/Models/SubscriptionSpec.swift
  Rocket.ChatTests/Models/UnmanagedMessageSpec.swift
Labels: 💎 release: beta

#2642 [NEW] Crop image before uploading avatar
  Rocket.Chat/Controllers/Preferences/Profile/EditProfileTableViewController.swift
  Rocket.Chat/Extensions/UIViewController/UIViewControllerExtension.swift
Labels: 👍 improvement

#2664 [IMPROVEMENT] Swipe to read messages with uniform colour
  Rocket.Chat/Controllers/Subscriptions/SubscriptionsList/SubscriptionsViewController.swift
Labels: 👍 improvement

#2684 [FIX] Don't group message with different alias
  Rocket.Chat/Controllers/Chat/MessagesViewModel.swift
Labels: 👍 improvement
